// SkippyFlight - Autonomous two-connector delivery shuttle for Space Engineers.
// Generated by MDK2 (Mal.Mdk2.PbPackager) from the SkippyFlight project - do not edit
// the deployed script by hand. Source of truth: SkippyFlight/Program.cs. Full docs in
// README.md / CHANGELOG.md.
// 
const string A="0.19.0";enum E{B,C,D}enum J{F,G,H,I}struct R{public Vector3D K,L,M,N;public long O;public double P,Q;}
enum f{S,T,U,V,W,X,Y,Z,a,b,c,d,e}struct h{public bool g;}enum l{i,j,Z,k}abstract class t{public abstract f m{get;}public
abstract bool n{get;}public abstract string o{get;}public virtual void q(Program p){}public abstract void r(Program p);public
virtual void s(Program p){}}class v:t{public override f m{get{return f.S;}}public override bool n{get{return false;}}public
override string o{get{return"Idle";}}public override void r(Program p){p.u();}}class x:t{public override f m{get{return f.T;}}
public override bool n{get{return false;}}public override string o{get{return"Recording";}}public override void r(Program p){p
.w();}}class ª:t{public override f m{get{return f.U;}}public override bool n{get{return false;}}public override string o{
get{return"Loading";}}public override void q(Program p){p.y.g=true;}public override void r(Program p){p.z();}}class À:t{
public override f m{get{return f.V;}}public override bool n{get{return true;}}public override string o{get{return"Undock";}}
public override void q(Program p){p.µ=0;}public override void r(Program p){p.º();}}class Ä:t{public override f m{get{return f.
W;}}public override bool n{get{return true;}}public override string o{get{return"Staging";}}public override void q(
Program p){p.Á=0;p.Â=false;}public override void r(Program p){p.Ã();}}class Ç:t{public override f m{get{return f.X;}}public
override bool n{get{return true;}}public override string o{get{return"Cruise";}}public override void q(Program p){p.Å=0;}public
override void r(Program p){p.Æ();}}class É:t{public override f m{get{return f.Y;}}public override bool n{get{return true;}}
public override string o{get{return"Climbing";}}public override void q(Program p){p.Å=0;}public override void r(Program p){p.È
();}}class Ë:t{public override f m{get{return f.Z;}}public override bool n{get{return true;}}public override string o{get
{return"Descending";}}public override void q(Program p){p.Å=0;}public override void r(Program p){p.Ê();}}class Ï:t{public
override f m{get{return f.a;}}public override bool n{get{return true;}}public override string o{get{return"Holding";}}public
override void q(Program p){p.Ì=0;p.Í=0;}public override void r(Program p){p.Î();}}class Ñ:t{public override f m{get{return f.b;}
}public override bool n{get{return true;}}public override string o{get{return"Taxi";}}public override void r(Program p){p
.Ð();}}class Ò:t{public override f m{get{return f.c;}}public override bool n{get{return true;}}public override string o{
get{return"Holding";}}public override void q(Program p){p.Ì=0;p.Í=0;}public override void r(Program p){p.Î();}}class Ô:t{
public override f m{get{return f.d;}}public override bool n{get{return false;}}public override string o{get{return"Unloading";
}}public override void q(Program p){p.y.g=false;}public override void r(Program p){p.Ó();}}class Ö:t{public override f m{
get{return f.e;}}public override bool n{get{return false;}}public override string o{get{return"FAULT";}}public override
void r(Program p){p.Õ();}}E Ø=E.B;J Ù=J.F,Ú=J.F;string Û="Skippy",Ü="SkippyShuttleNet",Ý="",Þ="[SF]",ß="auto",à="[SF:CAM]",á
="",â="",ã="",ä="",å="Idle",æ="",ç="";bool è=false,é=true,ê=false,ë=false,ì=false,í=false,î=false,ï=true,ð=true,ñ=false,ò
=false,Â=false,ó=false,ô=false,õ=false,ö,ø,ù,ú,û=false;float ü=100f,ý=100f,þ=100f,ÿ=5f,Ā=0f;double ā=0,Ă=95,ă=30,Ą=30,ą=
10,Ć=10,ć=25,Ĉ=250,ĉ=12,Ċ=15,ċ=15,Č=40,č=0.6,Ď=30,ď=4.0,Đ=3.0,đ=0,Ē=0,ē=0,µ=0,Ĕ=0,ĕ=0,Ė=-1,ė=-1,Ę=1.0,ę=0,Ě=double.
MaxValue,ě=1,Ĝ=1,ĝ=0,Ğ=0,ğ=0,Ì=0,Í=0,Á=0,Ġ=0,ġ,Ģ=0;R ģ,Ĥ;List<Vector3D>ĥ=new List<Vector3D>(),Ħ=new List<Vector3D>(),ħ=new List<
Vector3D>();List<string>Ĩ=new List<string>();f ĩ=f.S;h y;l Ī=l.k;Vector3D ī,Ĭ,ĭ,Į,į,İ,ı=Vector3D.Zero;public double Å=0;
Dictionary<f,t>Ĳ;double ĳ=0,Ĵ=0;List<Vector3D>ĵ=new List<Vector3D>();List<double>Ķ=new List<double>();int ķ=0,Ĺ=ĸ,ĺ=0;double Ļ=
9999;long ļ=0;R Ľ;bool ľ;const string Ŀ="full",ŀ="menu",Ł="status",ł="trip",Ń="telem";const int ĸ=0,ń=1,Ņ=2,ņ=3,Ň=4;Vector3D
ň;IMyRemoteControl ŉ;List<IMyShipConnector>Ŋ=new List<IMyShipConnector>();List<IMyCargoContainer>ŋ=new List<
IMyCargoContainer>();struct Ő{public IMyTextSurface Ō;public string ō;public float Ŏ,ŏ;}List<Ő>ő=new List<Ő>();IMyTextSurface Œ;List<
IMyGyro>œ=new List<IMyGyro>();List<IMyThrust>Ŕ=new List<IMyThrust>();List<IMyGasTank>ŕ=new List<IMyGasTank>();List<
IMyBatteryBlock>Ŗ=new List<IMyBatteryBlock>();List<IMyCameraBlock>ŗ=new List<IMyCameraBlock>();IMyBroadcastListener Ř;const double ř=
1.0/6.0,Ś=45,ś=2.5,Ŝ=0.95,ŝ=0.5,Ş=2.0,ş=0.03,Š=0.20,š=1.0,Ţ=8.0,ţ=0.5,Ť=0.10,ť=0.5,Ŧ=0.15,ŧ=0.12,Ũ=0.30,ũ=60.0,Ū=0.01,ū=
0.02,Ŭ=0.02,ŭ=0.05,Ů=0.10,ů=0.5,Ű=5.0,ű=0.4,Ų=1e-3,ų=2.0,Ŵ=100,ŵ=0.75,Ŷ=1.5,ŷ=10.0,Ÿ=0.70,Ź=1.5,ź=1.5,Ż=4.0,ż=5.0,Ž=5.0,ž=
6.0,ſ=2.0;double ƀ=ř,Ɓ=0;const int Ƃ=250,ƃ=26;
Program
(){Runtime.UpdateFrequency=UpdateFrequency.Update10;Ĳ=new Dictionary<f,t>{{f.S,new v()},{f.T,new x()},{f.U,new ª()},{f.V,
new À()},{f.W,new Ä()},{f.X,new Ç()},{f.Y,new É()},{f.Z,new Ë()},{f.a,new Ï()},{f.b,new Ñ()},{f.c,new Ò()},{f.d,new Ô()},{f
.e,new Ö()}};if(string.IsNullOrWhiteSpace(Me.CustomData))Ƅ();ƅ();Ɔ();Ƈ();ƈ();Ɖ();Ř=IGC.RegisterBroadcastListener(Ü);Ɗ=
true;Ƌ();}void
 Save
(){var ƌ=new MyIni();ƌ.TryParse(Me.CustomData);ƌ.Set("state","phase",(int)ĩ);ƌ.Set("state","outbound",y.g);ƌ.Set("state",
"tripStartHome",ï);ƌ.Set("state","operating",í);ƌ.Set("state","phaseTimer",µ);ƌ.Set("state","estHydroOut",ĳ);ƌ.Set("state","estBattOut"
,Ĵ);ƌ.Set("state","estHydroHome",Ĕ);ƌ.Set("state","estBattHome",ĕ);Me.CustomData=ƌ.ToString();}void
 Main
(string ƍ,UpdateType Ǝ){try{ƀ=Runtime.TimeSinceLastRun.TotalSeconds;if(ƀ<=0||ƀ>0.5)ƀ=ř;if(!string.IsNullOrEmpty(ƍ))Ə(ƍ.
Trim());if(ŉ==null){Ƈ();if(ŉ==null){å="No Remote Control found";Ɛ();return;}}Ƒ();Ļ+=ƀ;Ġ+=ƀ;Ĳ[ĩ].r(this);Runtime.
UpdateFrequency=Ĳ[ĩ].n?UpdateFrequency.Update1:UpdateFrequency.Update10;Ɓ+=ƀ;if(Ɓ>=0.15||!string.IsNullOrEmpty(ƍ)){Ɛ();ƒ();Ɓ=0;}}catch(
Exception Ɠ){ĩ=f.e;å="ERROR: "+Ɠ.Message;Echo(å);}}void ƕ(f Ɣ){if(Ɣ==ĩ)return;Ĳ[ĩ].s(this);ĩ=Ɣ;Ĳ[ĩ].q(this);ó=false;ô=false;ç="";
Ġ=ſ;if(Ɣ==f.V){ø=false;ù=false;ú=false;ġ=0;}}void Õ(){Ɩ();Ƌ();}string Ɨ(){switch(ĩ){case f.U:return"Loading";case f.V:
return y.g?"UndockHome":"UndockDest";case f.W:return y.g?"UndockHome":"UndockDest";case f.X:return y.g?"CruiseToDest":
"CruiseToHome";case f.Y:return y.g?"CruiseToDest":"CruiseToHome";case f.Z:return y.g?"CruiseToDest":"CruiseToHome";case f.a:return y.g
?"ApproachDest":"ApproachHome";case f.b:return y.g?"ApproachDest":"ApproachHome";case f.c:return y.g?"ApproachDest":
"ApproachHome";case f.d:return"Unloading";case f.T:return"Recording";case f.e:return"Faulted";default:return"Idle";}}void ƙ(string Ƙ){
switch(Ƙ){case"Loading":ĩ=f.U;y.g=true;break;case"UndockHome":ĩ=f.V;y.g=true;break;case"CruiseToDest":ĩ=f.X;y.g=true;break;
case"ApproachDest":ĩ=f.a;y.g=true;break;case"Unloading":ĩ=f.d;y.g=false;break;case"UndockDest":ĩ=f.V;y.g=false;break;case
"CruiseToHome":ĩ=f.X;y.g=false;break;case"ApproachHome":ĩ=f.a;y.g=false;break;case"Recording":ĩ=f.T;break;case"Faulted":ĩ=f.e;break;
default:ĩ=f.S;break;}}void Ə(string ƚ){var ƛ=ƚ.Split(new[]{' '},StringSplitOptions.RemoveEmptyEntries);var Ɯ=ƚ.ToUpperInvariant
().Split(new[]{' '},StringSplitOptions.RemoveEmptyEntries);if(Ɯ.Length==0)return;switch(Ɯ[0]){case"RECORD":if(Ɯ.Length>1
&&Ɯ[1]=="HOME")Ɲ(Ɯ.Length>2?ƛ[2]:"");else if(Ɯ.Length>1&&Ɯ[1]=="DEST")ƞ(Ɯ.Length>2?ƛ[2]:"");else if(Ɯ.Length>1&&Ɯ[1]==
"ZONE")Ɵ();else å="Usage: RECORD HOME [name] | RECORD DEST | RECORD ZONE";break;case"START":case"GO":if(!ê){å=
"No route - RECORD HOME/DEST first";break;}í=true;if(ĩ==f.S||ĩ==f.e){bool ơ=Ơ();if(ơ&&!Ƣ()){í=false;å=
"START: not at a route dock - move to home/dest first";break;}bool Ƥ=ƣ();ï=!(ơ&&!Ƥ);if(Ø==E.D){if(ơ&&Ƥ)ƕ(f.U);else if(ơ){y.g=false;ƕ(f.V);}else if(Ƥ){y.g=true;ƕ(f.X);}else{y.
g=false;ƕ(f.X);}}else{if(ơ&&Ƥ)ƕ(f.U);else if(ơ)ƕ(f.d);else{y.g=false;ƕ(f.X);}}µ=0;î=false;}å="Started ("+ƥ(Ø)+")";break;
case"STOP":í=false;î=false;Ɩ();Ƌ();ƕ(f.S);å="Stopped";break;case"HOME":if(!ê){å="No route - RECORD HOME/DEST first";break;}Ɩ
();if(Ơ()&&ƣ()){í=false;ƕ(f.S);å="Already home";}else{í=true;y.g=false;ƕ(Ơ()?f.V:f.X);å="Returning home";}break;case
"MODE":if(Ɯ.Length>1)Ʀ(Ɯ[1]);else å="Mode: "+ƥ(Ø);break;case"DEPART":Ƨ();break;case"RESUME":Ɖ();å="Resumed: "+Ɨ();break;case
"CLEARROUTE":ƨ();å="Route cleared";break;case"ROUTE":if(Ɯ.Length>1){if(í)å="STOP before switching routes";else Ʃ(ƛ[1]);}else å=
"Active: "+(ã==""?"none":ã)+" ("+Ĩ.Count+" saved)";break;case"DELROUTE":if(Ɯ.Length>1)ƪ(ƛ[1]);else å="Usage: DELROUTE <name>";
break;case"UP":ƫ(-1);break;case"DOWN":ƫ(+1);break;case"APPLY":Ƭ();break;case"BACK":ƭ();break;default:å="Unknown command: "+Ɯ[
0];break;}}void Ʀ(string Ʈ){switch(Ʈ){case"CONTINUOUS":Ø=E.B;break;case"ONETRIP":Ø=E.C;break;case"ONEWAY":Ø=E.D;break;
case"WAITFULL":Ø=E.B;Ù=J.G;Ư("runMode","CONTINUOUS");Ư("homeTrigger","Cargo");å=
"WaitFull -> Continuous + Home trigger = Cargo";return;default:å="Mode must be CONTINUOUS|ONETRIP|ONEWAY";return;}var ƌ=new MyIni();ƌ.TryParse(Me.CustomData);ƌ.Set(
"sf","runMode",Ʈ);Me.CustomData=ƌ.ToString();å="Mode = "+ƥ(Ø);}string ƥ(E Ʈ){return Ʈ==E.C?"OneTrip":Ʈ==E.D?"OneWay":
"Continuous";}string Ʊ(J ư){return ư==J.G?"Cargo":ư==J.H?"Timer":ư==J.I?"Manual":"Auto";}void Ɲ(string Ƙ=""){var Ƴ=Ʋ();if(Ƴ==null){å
="RECORD HOME: dock at the home connector first";return;}string Ƶ=ƴ(Ƙ);ä=Ƶ!=""?Ƶ:(ã!=""?ã:"Main");ģ=ƶ(Ƴ);á=Ƴ.CustomName;ĥ
.Clear();ň=ģ.K;ı=Vector3D.Zero;ƕ(f.T);í=false;å="Recording '"+ä+"' from "+á+". Fly to destination.";}void ƞ(string Ƙ=""){
if(ĩ!=f.T){å="RECORD DEST: run RECORD HOME first";return;}var Ƴ=Ʋ();if(Ƴ==null){å=
"RECORD DEST: dock at the destination connector first";return;}string Ƶ=ƴ(Ƙ);if(Ƶ!="")ä=Ƶ;Ĥ=ƶ(Ƴ);â=Ƴ.CustomName;if(ĥ.Count==0||Vector3D.Distance(ĥ[ĥ.Count-1],Ĥ.K)>5)Ʒ(ŉ.
GetPosition());ê=true;ã=ä!=""?ä:"Main";ƕ(f.S);Ƹ();å="Saved '"+ã+"': "+á+" -> "+â+" ("+ĥ.Count+"wp)";}void Ɵ(){if(ĩ!=f.T){å=
"RECORD ZONE: run RECORD HOME first";return;}Ĥ=new R{K=ŉ.GetPosition(),L=ŉ.WorldMatrix.Forward,M=ŉ.WorldMatrix.Up,N=ŉ.WorldMatrix.Forward,O=ļ,Q=ŉ.
GetNaturalGravity().Length()};â="ZONE";ë=true;if(ĥ.Count==0||Vector3D.Distance(ĥ[ĥ.Count-1],Ĥ.K)>5)Ʒ(ŉ.GetPosition());ê=true;ã=ä!=""?ä:
"Main";ƕ(f.S);Ƹ();å="Saved '"+ã+"': "+á+" -> ZONE ("+ĥ.Count+"wp)";}R ƶ(IMyShipConnector Ƴ){return new R{K=ŉ.GetPosition(),L=ŉ
.WorldMatrix.Forward,M=ŉ.WorldMatrix.Up,N=Ƴ.WorldMatrix.Forward,O=(Ƴ.Status==MyShipConnectorStatus.Connected&&Ƴ.
OtherConnector!=null)?Ƴ.OtherConnector.CubeGrid.EntityId:0,Q=ŉ.GetNaturalGravity().Length()};}R ƹ(){return õ?Ľ:Ĥ;}void w(){Vector3D p=
ŉ.GetPosition();double ƺ=Vector3D.Distance(p,ň);if(ƺ<20)return;Vector3D ƻ=Vector3D.Normalize(p-ň);double Ƽ=ı==Vector3D.
Zero?0:Math.Acos(MathHelper.Clamp(ƻ.Dot(ı),-1,1))*180.0/Math.PI;if(ƺ>=Ĉ||(ƺ>=30&&Ƽ>=ĉ))Ʒ(p);}void Ʒ(Vector3D p){if(Ċ>0&&ĥ.
Count>=2){Vector3D ƽ=ĥ[ĥ.Count-2];Vector3D ƾ=p-ƽ;double ƿ=ƾ.Length();if(ƿ>1e-3){Vector3D ǀ=ƾ/ƿ;Vector3D ǁ=ĥ[ĥ.Count-1]-ƽ;
double ǂ=ǁ.Dot(ǀ);double ǃ=(ǁ-ǂ*ǀ).Length();if(ǃ<=Ċ&&ǂ>=0&&ǂ<=ƿ){ĥ[ĥ.Count-1]=p;ň=p;ı=ǀ;return;}}}if(ĥ.Count>=Ƃ){å=
"Path full ("+Ƃ+" wp) - raise segMeters/simplifyMeters";return;}if(ĥ.Count>0)ı=Vector3D.Normalize(p-ň);ĥ.Add(p);ň=p;}void u(){Ɩ();Ƌ()
;if(!í)return;µ=0;if(Ơ()){if(!Ƣ()){å="Idle: docked away from route - undock or move to home/dest";return;}ƕ(ƣ()?f.U:f.d);
}else{í=false;å="Idle: not docked - issue START or dock at home/dest first";}}void z(){µ+=ƀ;double ǅ=Ǆ();double Ǉ=ǆ();
bool ǈ=ā>0&&ǅ>=ā*0.98;bool ǉ=Ǉ>=Ă||ǈ;if(Ǌ(true,ǉ)){string ǋ;if(!ǌ(true,out ǋ)){å=ǋ;return;}if(!î&&!Ǎ("DEPART",á)){å=ǎ(
"DEPART");return;}î=false;Ǐ(true);å="Loaded ("+Ǉ.ToString("0")+"%, "+(ǅ/1000.0).ToString("0.0")+"t) - departing";ƕ(f.V);µ=0;
return;}å=ǐ(true,Ǉ);}void Ó(){µ+=ƀ;double Ǉ=ǆ();bool ǉ=Ǉ<=1.0;if(Ø==E.D){if(!ǉ&&!î){å=ǐ(false,Ǉ);return;}î=false;µ=0;í=false;ƕ
(f.S);å="Delivered - holding at destination";return;}if(Ǌ(false,ǉ)){string ǋ;if(!ǌ(false,out ǋ)){å=ǋ;return;}if(!î&&!Ǎ(
"DEPART",â)){å=ǎ("DEPART");return;}î=false;Ǐ(false);µ=0;ƕ(f.V);return;}å=ǐ(false,Ǉ);}bool Ǌ(bool Ƥ,bool ǉ){if(î)return true;J Ǒ=
Ƥ?Ù:Ú;switch(Ǒ){case J.I:return false;case J.H:return µ>=Ą;case J.G:return ǉ;default:return ǉ||(!Ƥ&&µ>=ă);}}string ǐ(bool
Ƥ,double Ǉ){string ǒ=(Ƥ?"Loading ":"Unloading ")+Ǉ.ToString("0")+"%";J Ǒ=Ƥ?Ù:Ú;if(Ǒ==J.I)return ǒ+" - waiting DEPART";if(
Ǒ==J.H)return ǒ+" - dwell "+µ.ToString("0")+"/"+Ą.ToString("0")+"s";return ǒ;}void º(){bool Ǔ=y.g;var Ƴ=ǔ(Ǔ?á:â);R p=Ǔ?ģ:
ƹ();if(Ƴ!=null&&Ƴ.Status==MyShipConnectorStatus.Connected){Vector3D Ǖ=ŉ.GetNaturalGravity();if(Ǖ.LengthSquared()>Ų*Ų){ǖ()
;double ǅ=ŉ.CalculateShipMass().PhysicalMass;Ǘ(-Ǖ*ǅ);µ+=ƀ;å="Spinning up thrust";if(!ǘ(Ǖ,ǅ)&&µ<ś)return;}Ƴ.Disconnect();µ
=0;å="Undocking";return;}bool Ǜ=Ǚ(ǚ(p),p.L,p.M,1.0);µ+=ƀ;å=Ǔ?"Clearing home dock":"Clearing station dock";if(Ǜ||µ>=Ś){Ƌ()
;µ=0;ƕ(f.W);}}void Ã(){bool Ǔ=y.g;R p=Ǔ?ģ:ƹ();if(!Ǔ&&ë&&ö&&!ù){if(!ø)ǜ(true);if(!ǝ()){å="Threading out to zone";return;}ø
=false;ù=true;İ=ŉ.GetPosition();ú=true;Ƌ();}Vector3D ǟ=(!Ǔ&&ë&&ù&&ú)?İ:Ǟ(p);double Ǡ=Vector3D.Distance(ŉ.GetPosition(),ǟ)
;if(!Â&&Ǡ<3.0)Â=true;else if(Â&&Ǡ>8.0)Â=false;Vector3D ǡ=p.L,Ǣ=p.M;if(Â){Vector3D Ǥ=ǣ(Ǔ)-ǟ;if(Ǥ.LengthSquared()>1){
Vector3D ƻ=Vector3D.Normalize(Ǥ);Vector3D Ǖ=ŉ.GetNaturalGravity();if(Ǖ.LengthSquared()>1e-3&&ǥ()){Vector3D Ǧ=Vector3D.Normalize(
-Ǖ);Vector3D ǧ=ƻ-ƻ.Dot(Ǧ)*Ǧ;if(ǧ.LengthSquared()>1e-6)ǡ=Vector3D.Normalize(ǧ);Ǣ=Ǧ;}else{ǡ=ƻ;if(Ǖ.LengthSquared()>1e-3){
Vector3D Ǩ=-Ǖ;Vector3D ǃ=Ǩ-Ǩ.Dot(ƻ)*ƻ;Ǣ=ǃ.LengthSquared()>1e-6?Vector3D.Normalize(ǃ):ŉ.WorldMatrix.Up;}else{Ǣ=ŉ.WorldMatrix.Up;}
}}}if(Â){double Ǫ=ǩ(ǡ,Ǣ,true);ǫ(ǟ);bool Ǭ=Ǫ<Ů&&Ǡ<3.0;if(Ǭ)Á+=ƀ;else Á=0;å="Staging - aligning for cruise";}else{Ǚ(ǟ,ǡ,Ǣ,
1.0);Á=0;å=Ǔ?"Departing home":"Departing station";}µ+=ƀ;if(Á>=ź||µ>=Ś){Ƌ();µ=0;Â=false;ƕ(ǭ());}}Vector3D ǣ(bool Ǯ){ǯ(Ǯ);
return ĵ[0];}void Æ(){ǰ();}void È(){ǰ();}void Ê(){ǰ();}void ǰ(){bool Ǯ=y.g;if(!Ǳ(Ǯ)){ǲ(Ǯ);return;}ę+=ƀ;bool ǳ=ǝ();å=Ǵ();if(y.g
&&ë&&ǵ(ŉ.GetPosition())){İ=ŉ.GetPosition();ú=true;Ƕ=false;Ƌ();ƕ(f.a);µ=0;return;}if(ǳ){Ƕ=false;Ƌ();ƕ(f.a);µ=0;return;}if(ę
>=ũ){Ƕ=false;Ƌ();ƕ(f.e);å="Cruise stuck - check thrust/gyro/geometry";return;}if(Ƿ())ƕ(Ǹ());}double ǹ(){if(ø)return ÿ;if(ĩ
==f.Y)return ý;if(ĩ==f.Z)return þ;return ü;}bool Ǻ(){return ĩ==f.X||ĩ==f.Y||ĩ==f.Z;}string Ǵ(){bool Ǯ=y.g;string ǻ=ĩ==f.Y?
"Climbing":ĩ==f.Z?"Descending":"Cruising";string ǽ=Ǽ()?" handoff":"";return ǻ+(Ǯ?" to destination":" home")+ǽ;}bool Ǽ(){return ŉ!=
null&&ŉ.GetNaturalGravity().Length()>Ų&&(ĩ==f.Y||ĩ==f.Z);}l ȁ(double Ǿ,double ǿ){bool Ȁ=Ǿ>Ų,ư=ǿ>Ų;if(Ȁ&&ư)return l.i;if(Ȁ&&!
ư)return l.j;if(!Ȁ&&ư)return l.Z;return l.k;}l Ȃ(){double Ǿ=y.g?ģ.Q:Ĥ.Q;double ǿ=y.g?Ĥ.Q:ģ.Q;return ȁ(Ǿ,ǿ);}f ǭ(){Ī=Ȃ();
return(Ī==l.i||Ī==l.j)?f.Y:f.X;}f Ǹ(){if(ĩ==f.Y)return f.X;if(ĩ==f.X)return f.Z;return ĩ;}bool ȃ(out double ƽ){ƽ=0;return ŉ!=
null&&ŉ.TryGetPlanetElevation(MyPlanetElevation.Sealevel,out ƽ);}bool Ƿ(){if(ŉ==null)return false;double Ȅ=ŉ.
GetNaturalGravity().Length();double ȅ;bool Ȇ=ȃ(out ȅ);ē=(Ȇ&&ì&&ƀ>0)?(ȅ-Ē)/ƀ:0;Ē=ȅ;ì=Ȇ;if(ĩ==f.Y){if(Ī==l.i){bool ȇ=Vector3D.Distance(ŉ.
GetPosition(),ī)>Ŵ&&ē<ŵ;Å=ȇ?Å+ƀ:0;return Å>=ų;}Å=Ȅ<Ų?Å+ƀ:0;return Å>=ų;}if(ĩ==f.X){if(Ī==l.i){Å=ē<-Ŷ?Å+ƀ:0;return Å>=ų;}if(Ī==l.Z){
Å=Ȅ>Ų?Å+ƀ:0;return Å>=ų;}return false;}return false;}bool Ȉ=false;bool Ƕ=false;bool Ǳ(bool Ǯ){return Ƕ&&Ȉ==Ǯ;}Vector3D ǚ(
R p){return p.K-p.N*ċ;}double Ȋ(R p){double ȉ=p.P>0?p.P:Č;return Math.Max(ȉ,ċ+5);}Vector3D Ǟ(R p){return p.K-p.N*Ȋ(p);}
void ǲ(bool Ǯ){ǯ(Ǯ);if(ĵ.Count==0){ƕ(f.e);å="Cruise: empty path - re-record route";return;}ȋ();Ī=Ȃ();ī=ŉ.GetPosition();Å=0;Ē
=0;ì=false;ē=0;ķ=0;ę=0;Ě=double.MaxValue;Ì=0;Í=0;ø=false;Ƕ=true;Ȉ=Ǯ;å=Ǯ?"Cruising to destination":"Cruising home";}void ǜ
(bool Ȍ){ĵ.Clear();if(Ȍ)for(int ȍ=Ħ.Count-1;ȍ>=0;ȍ--)ĵ.Add(Ħ[ȍ]);else{for(int ȍ=0;ȍ<Ħ.Count;ȍ++)ĵ.Add(Ħ[ȍ]);ĵ.Add(ƹ().K);
}if(ĵ.Count==0)ĵ.Add(ŉ.GetPosition());ȋ();ķ=0;ę=0;Ě=double.MaxValue;ø=true;Ƕ=false;}void ǯ(bool Ǯ){ĵ.Clear();if(Ǯ){õ=
false;Ħ.Clear();ö=false;}R Ȏ=Ǯ?ģ:Ĥ;R ȏ=Ǯ?Ĥ:ģ;double Ȑ=Ȋ(Ȏ)+3;double ȑ=Ȋ(ȏ)+3;if(Ǯ){for(int ȍ=0;ȍ<ĥ.Count;ȍ++)if(Vector3D.
Distance(ĥ[ȍ],Ȏ.K)>Ȑ&&Vector3D.Distance(ĥ[ȍ],ȏ.K)>ȑ)ĵ.Add(ĥ[ȍ]);}else{for(int ȍ=ĥ.Count-1;ȍ>=0;ȍ--)if(Vector3D.Distance(ĥ[ȍ],Ȏ.K
)>Ȑ&&Vector3D.Distance(ĥ[ȍ],ȏ.K)>ȑ)ĵ.Add(ĥ[ȍ]);}ĵ.Add(Ǟ(ȏ));}void ȋ(){int Ƶ=ĵ.Count;Ķ.Clear();for(int ȍ=0;ȍ<Ƶ;ȍ++)Ķ.Add(ü
);if(Ƶ==0)return;double[]Ȓ;MatrixD ȓ;Ȕ(out Ȓ,out ȓ);double ȕ=Ȓ[0];for(int ȍ=1;ȍ<6;ȍ++)ȕ=Math.Min(ȕ,Ȓ[ȍ]);double ǅ=ŉ.
CalculateShipMass().PhysicalMass;Ę=Math.Max(ţ,č*ȕ/Math.Max(ǅ,1.0));for(int ȍ=1;ȍ<Ƶ-1;ȍ++){Vector3D Ȗ=ĵ[ȍ]-ĵ[ȍ-1];Vector3D ȗ=ĵ[ȍ+1]-ĵ[ȍ];
if(Ȗ.LengthSquared()<1e-6||ȗ.LengthSquared()<1e-6)continue;Ȗ=Vector3D.Normalize(Ȗ);ȗ=Vector3D.Normalize(ȗ);double Ș=Math.
Acos(MathHelper.Clamp(Ȗ.Dot(ȗ),-1,1));if(Ș<Ť)continue;double ș=Ď/Math.Max(Math.Tan(Ș*0.5),1e-3);double Ț=Math.Sqrt(Ę*ș);Ķ[ȍ]
=Math.Min(Ķ[ȍ],Math.Min(Ț,ü));}Ķ[Ƶ-1]=š;for(int ȍ=Ƶ-2;ȍ>=0;ȍ--){double ț=Vector3D.Distance(ĵ[ȍ],ĵ[ȍ+1]);double Ȝ=Math.
Sqrt(Ķ[ȍ+1]*Ķ[ȍ+1]+2.0*Ę*ț);Ķ[ȍ]=Math.Min(Ķ[ȍ],Math.Min(Ȝ,ü));}}double ȝ(){return Math.Max(Ţ,ŉ.GetShipSpeed()*ƀ*2.0);}void ȣ
(Vector3D Ȟ){while(ķ<ĵ.Count-1){Vector3D ȟ=ĵ[ķ];Vector3D Ɣ=ĵ[ķ+1];bool Ƞ=Vector3D.Distance(Ȟ,ȟ)<ȝ();Vector3D ȡ=Ɣ-ȟ;bool Ȣ
=ȡ.LengthSquared()>1e-6&&(Ȟ-ȟ).Dot(Vector3D.Normalize(ȡ))>0;if(Ƞ||Ȣ){ķ++;ę=0;Ě=double.MaxValue;}else break;}}bool ǝ(){Ȥ(
false);Vector3D Ȟ=ŉ.GetPosition();Vector3D ȥ=ŉ.GetShipVelocities().LinearVelocity;Vector3D Ǖ=ŉ.GetNaturalGravity();double ǅ=ŉ
.CalculateShipMass().PhysicalMass;ȣ(Ȟ);Vector3D Ȧ=ĵ[ķ];Vector3D ȧ=Ȧ-Ȟ;double Ȩ=ȧ.Length();Vector3D ȩ=Ȩ>1e-3?ȧ/Ȩ:ŉ.
WorldMatrix.Forward;if(Ȩ<Ě-1.0){Ě=Ȩ;ę=0;}if(ķ<ĵ.Count-1&&Ȩ<Ď){Vector3D Ȫ=ĵ[ķ+1]-Ȧ;if(Ȫ.LengthSquared()>1e-6){Vector3D ȫ=Vector3D.
Normalize(Ȫ);double Ȭ=1.0-Ȩ/Ď;Vector3D ȭ=Vector3D.Lerp(ȩ,ȫ,Ȭ);if(ȭ.LengthSquared()>1e-6)ȩ=Vector3D.Normalize(ȭ);}}double Ȯ=Ķ[ķ];
double ȯ=Math.Sqrt(Ȯ*Ȯ+2.0*Ę*Ȩ);double Ȱ=Math.Min(ǹ(),ȯ);Vector3D ȱ,Ȳ;bool ȳ=Ǖ.LengthSquared()>1e-3;if(ȳ&&ǥ()){Vector3D Ǧ=
Vector3D.Normalize(-Ǖ);Vector3D ǧ=ȩ-ȩ.Dot(Ǧ)*Ǧ;ȱ=ǧ.LengthSquared()>1e-6?Vector3D.Normalize(ǧ):ŉ.WorldMatrix.Forward;Ȳ=Ǧ;}else if
(ȳ){Vector3D Ǩ=-Ǖ;Vector3D ǃ=Ǩ-Ǩ.Dot(ȩ)*ȩ;ȱ=ȩ;Ȳ=ǃ.LengthSquared()>1e-6?Vector3D.Normalize(ǃ):ŉ.WorldMatrix.Up;}else{ȱ=ȩ;Ȳ
=ŉ.WorldMatrix.Up;}double Ǫ=ǩ(ȱ,Ȳ,true);double ȴ=ŉ.WorldMatrix.Forward.Cross(ȱ).Length();double ȶ=ȵ(1.0-Math.Max(0.0,ȴ-ŧ)
/ť,Ŧ,1.0);double ȷ=ȥ.Length();double ȸ=ȷ<1.0?1.0:ȵ((ȥ/ȷ).Dot(ȩ),Ũ,1.0);ě=ȶ;Ĝ=ȸ;ĝ=ȯ;Ğ=ǹ();Ȱ*=ȶ*ȸ;Vector3D ȹ=ȩ*Ȱ;Vector3D Ⱥ
=ȹ-ȥ;bool Ȼ=Ǖ.LengthSquared()<1e-3;if(Ȼ&&Ǫ<Š&&Ⱥ.Length()<ů)ȼ();else{double Ƚ=Ⱥ.Dot(ȩ);if(Ƚ<0.0&&Ƚ>-Ű)Ⱥ-=Ƚ*ȩ;if(Ⱥ.Length()
<ű)Ⱥ=Vector3D.Zero;Ǘ(Ⱥ*ǅ*Ş-Ǖ*ǅ);}bool Ⱦ=ķ==ĵ.Count-1;return Ⱦ&&Ȩ<ȝ()&&ȷ<š;}void Î(){bool Ǯ=y.g;R p=Ǯ?ƹ():ģ;if(Ǯ&&ë){if(!ú
){İ=ŉ.GetPosition();ú=true;}ǫ(İ);ǩ(ŉ.WorldMatrix.Forward,ŉ.WorldMatrix.Up,true);if(!Ǎ("LAND",â)){ġ=0;å=
"Loitering in zone - "+ǎ("LAND");return;}ġ+=ƀ;if(!ö&&ġ<Ż){å="Cleared - awaiting interior path";return;}µ=0;ƕ(f.b);return;}Vector3D ȿ=Ǟ(p);
Vector3D Ǖ=ŉ.GetNaturalGravity();bool ȳ=Ǖ.LengthSquared()>1e-3;double ȷ=ŉ.GetShipVelocities().LinearVelocity.Length();Vector3D ǡ
,Ǣ;if(ȳ&&ȷ>=š){Vector3D Ǧ=Vector3D.Normalize(-Ǖ);Vector3D ɀ=ŉ.WorldMatrix.Forward;Vector3D ǧ=ɀ-ɀ.Dot(Ǧ)*Ǧ;ǡ=ǧ.
LengthSquared()>1e-6?Vector3D.Normalize(ǧ):ɀ;Ǣ=Ǧ;}else{ǡ=p.L;Ǣ=p.M;}if(Ɂ(p)){Í=0;Ì+=ƀ;Ǚ(ȿ,ǡ,Ǣ,1.0);å=(Ǯ?"Holding at destination":
"Holding at home")+" - dock blocked ("+Ì.ToString("0")+"s)";if(đ>0&&Ì>=đ){Ƌ();ƕ(f.e);å="Dock blocked - gave up after "+đ.ToString("0")+
"s";}return;}bool Ǭ=Ǚ(ȿ,ǡ,Ǣ,1.0);if(Ì>0){Í+=ƀ;if(Í<Ź){å=(Ǯ?"Dock clearing at destination":"Dock clearing at home")+
" - confirming";return;}Ì=0;}å=(Ǯ?"Holding at destination":"Holding at home")+" - cleared";if(Ǭ){if(!Ǎ("LAND",Ǯ?â:á)){å=(Ǯ?
"Holding at destination":"Holding at home")+" - "+ǎ("LAND");return;}µ=0;ƕ(f.b);}}void Ð(){bool Ǯ=y.g;var Ƴ=ǔ(Ǯ?â:á);R p=Ǯ?ƹ():ģ;if(Ƴ!=null&&!Ƴ.
Enabled)Ƴ.Enabled=true;if(Ƴ!=null&&Ƴ.Status==MyShipConnectorStatus.Connected){Ɩ();Ƌ();Ƴ.Connect();µ=0;ɂ();return;}if(Ƴ!=null&&Ƴ
.Status==MyShipConnectorStatus.Connectable)Ƴ.Connect();if(ŉ.IsAutoPilotEnabled)Ɩ();if(Ǯ&&ë&&ö&&!ù){if(!ø)ǜ(false);if(!ǝ()
){å="Threading to pad";return;}ø=false;ù=true;Ƌ();}if(Ɂ(p)){Ì=0;Í=0;µ=0;ƕ(f.a);å=Ǯ?
"Taxi aborted - corridor blocked at destination":"Taxi aborted - corridor blocked at home";return;}Ǚ(p.K,p.L,p.M,0.3);µ+=ƀ;å=(Ǯ?"Docking at destination":
"Docking at home")+" ("+Vector3D.Distance(ŉ.GetPosition(),p.K).ToString("0")+"m)";if(µ>=Ś){Ɩ();Ƌ();ƕ(f.e);å=
"Docking timed out - check approach geometry";}}bool Ǚ(Vector3D Ȟ,Vector3D ɀ,Vector3D Ǩ,double Ƀ){Ȥ(false);double Ǫ=ǩ(ɀ,Ǩ);Vector3D Ǥ=Ȟ-ŉ.GetPosition();double Ȩ=Ǥ.
Length();Vector3D Ǖ=ŉ.GetNaturalGravity();double ǅ=ŉ.CalculateShipMass().PhysicalMass;Vector3D ȹ=Vector3D.Zero;if(Ǫ<Š&&Ȩ>0.05)
{double Ʉ=Math.Min((double)ÿ,Ȩ*ŝ);ȹ=Ǥ/Ȩ*Ʉ;}Vector3D ȥ=ŉ.GetShipVelocities().LinearVelocity;Vector3D Ⱥ=ȹ-ȥ;if(ȹ.Length()<ű
&&Ⱥ.Length()<ű)Ⱥ=Vector3D.Zero;Ǘ(Ⱥ*ǅ*Ş-Ǖ*ǅ);return Ȩ<=Ƀ&&Ǫ<ş&&ȥ.Length()<š;}void ǫ(Vector3D Ȟ){Ȥ(false);Vector3D Ǥ=Ȟ-ŉ.
GetPosition();double Ȩ=Ǥ.Length();Vector3D Ǖ=ŉ.GetNaturalGravity();double ǅ=ŉ.CalculateShipMass().PhysicalMass;Vector3D ȹ=Vector3D.
Zero;if(Ȩ>0.05){double Ʉ=Math.Min((double)ÿ,Ȩ*ŝ);ȹ=Ǥ/Ȩ*Ʉ;}Vector3D ȥ=ŉ.GetShipVelocities().LinearVelocity;Vector3D Ⱥ=ȹ-ȥ;if(
ȹ.Length()<ű&&Ⱥ.Length()<ű)Ⱥ=Vector3D.Zero;Ǘ(Ⱥ*ǅ*Ş-Ǖ*ǅ);}double ǩ(Vector3D Ʌ,Vector3D Ɇ)=>ǩ(Ʌ,Ɇ,ɇ(),false);double ǩ(
Vector3D Ʌ,Vector3D Ɇ,bool Ɉ)=>ǩ(Ʌ,Ɇ,ɇ(),Ɉ);double ǩ(Vector3D Ʌ,Vector3D Ɇ,double ɉ,bool Ɉ){Vector3D ɀ=ŉ.WorldMatrix.Forward,Ǩ=ŉ
.WorldMatrix.Up;Vector3D Ɋ=ɀ.Cross(Ʌ);if(ɀ.Dot(Ʌ)<0.0){double ɋ=Ɋ.Length();Ɋ=ɋ>1e-6?Ɋ/ɋ:Vector3D.Normalize(Ǩ);}Vector3D Ɍ
=Ǩ.Cross(Ɇ);if(Ǩ.Dot(Ɇ)<0.0){double ɋ=Ɍ.Length();Ɍ=ɋ>1e-6?Ɍ/ɋ:Vector3D.Normalize(ɀ);}Vector3D ɍ=Ɋ+Ɍ;double Ɏ=Ɋ.Length()+Ɍ
.Length();ğ=Ɏ;Vector3D ɏ=ŉ.GetShipVelocities().AngularVelocity;if(Ɉ){bool ɐ=ò?Ɏ<Ů:(Ɏ<ŭ&&ɏ.Length()<Ŭ*2.0);if(ɐ){ò=true;ɑ(
);return Ɏ;}ò=false;}else{ò=false;if(Ɏ<ū&&ɏ.Length()<Ŭ){ɑ();return Ɏ;}}if(ɍ.Length()<Ū)ɍ=Vector3D.Zero;Vector3D ɒ=ɍ*ď-ɏ*Đ
;double Ʈ=ɒ.Length();if(Ʈ>ɉ&&Ʈ>1e-6)ɒ*=ɉ/Ʈ;foreach(var ɓ in œ){if(ɓ==null||!ɓ.IsWorking)continue;Vector3D ɔ=Vector3D.
TransformNormal(ɒ,MatrixD.Transpose(ɓ.WorldMatrix));ɓ.GyroOverride=true;ɓ.Pitch=(float)(-ɔ.X);ɓ.Yaw=(float)(-ɔ.Y);ɓ.Roll=(float)(-ɔ.Z);
}return Ɏ;}void ɑ(){foreach(var ɓ in œ)if(ɓ!=null&&ɓ.IsWorking){ɓ.GyroOverride=true;ɓ.Pitch=0f;ɓ.Yaw=0f;ɓ.Roll=0f;}}
double ɇ(){double ɕ=Ā>0?Ā:(Me.CubeGrid.GridSizeEnum==MyCubeSize.Small?15.0:5.0);return ɕ*2.0*Math.PI/60.0;}void Ǘ(Vector3D ɖ){
if(ŉ==null)return;if(!ɗ(ɖ)){ȼ();return;}double[]Ȓ;MatrixD ȓ;Ȕ(out Ȓ,out ȓ);Vector3D ɘ=Vector3D.TransformNormal(ɖ,ȓ);double
[]ə=new double[6];ə[0]=Math.Max(0,ɘ.X);ə[1]=Math.Max(0,-ɘ.X);ə[2]=Math.Max(0,ɘ.Y);ə[3]=Math.Max(0,-ɘ.Y);ə[4]=Math.Max(0,ɘ
.Z);ə[5]=Math.Max(0,-ɘ.Z);foreach(var ư in Ŕ){if(ư==null||!ư.IsWorking)continue;int ɛ=ɚ(ư,ȓ);if(Ȓ[ɛ]<=1e-3||ə[ɛ]<=1e-3){ư
.ThrustOverride=0f;continue;}double ɜ=ə[ɛ]*(ư.MaxEffectiveThrust/Ȓ[ɛ]);ư.ThrustOverride=(float)Math.Min(ɜ,ư.
MaxEffectiveThrust);}}static bool ɗ(Vector3D ɝ){return!double.IsNaN(ɝ.X)&&!double.IsNaN(ɝ.Y)&&!double.IsNaN(ɝ.Z)&&!double.IsInfinity(ɝ.X)
&&!double.IsInfinity(ɝ.Y)&&!double.IsInfinity(ɝ.Z);}void Ȕ(out double[]Ȓ,out MatrixD ȓ){ȓ=MatrixD.Transpose(ŉ.WorldMatrix)
;Ȓ=new double[6];foreach(var ư in Ŕ)if(ư!=null&&ư.IsWorking)Ȓ[ɚ(ư,ȓ)]+=ư.MaxEffectiveThrust;}int ɚ(IMyThrust ư,MatrixD ȓ)
{Vector3D ɞ=Vector3D.TransformNormal(ư.WorldMatrix.Backward,ȓ);double ɟ=Math.Abs(ɞ.X),ɠ=Math.Abs(ɞ.Y),ɡ=Math.Abs(ɞ.Z);if(
ɟ>=ɠ&&ɟ>=ɡ)return ɞ.X>=0?0:1;if(ɠ>=ɡ)return ɞ.Y>=0?2:3;return ɞ.Z>=0?4:5;}bool ǥ(){if(ß=="level")return true;if(ß=="nose"
)return false;double[]Ȓ;MatrixD ȓ;Ȕ(out Ȓ,out ȓ);double Ǩ=Ȓ[2],ɀ=Ȓ[5];if(!ñ&&Ǩ>ɀ*1.1)ñ=true;else if(ñ&&Ǩ<ɀ*0.9)ñ=false;
return ñ;}void Ƌ(){foreach(var ư in Ŕ)if(ư!=null)ư.ThrustOverride=0f;foreach(var ɓ in œ)if(ɓ!=null){ɓ.GyroOverride=false;ɓ.
Pitch=0f;ɓ.Yaw=0f;ɓ.Roll=0f;}foreach(var ɢ in ŗ)if(ɢ!=null)ɢ.EnableRaycast=false;Ì=0;Í=0;Ȥ(true);}void ȼ(){foreach(var ư in Ŕ
)if(ư!=null)ư.ThrustOverride=0f;}void ǖ(){foreach(var ư in Ŕ)if(ư!=null&&!ư.Enabled)ư.Enabled=true;foreach(var Ȭ in Ŗ)if(
Ȭ!=null)Ȭ.ChargeMode=ChargeMode.Auto;}bool ǘ(Vector3D Ǖ,double ǅ){double ɓ=Ǖ.Length();if(ɓ<Ų)return true;Vector3D Ǩ=-Ǖ/ɓ;
double ɣ=0;foreach(var ư in Ŕ){if(ư==null||!ư.IsWorking)continue;double ɤ=ư.WorldMatrix.Backward.Dot(Ǩ);if(ɤ>0)ɣ+=ư.
CurrentThrust*ɤ;}return ɣ>=ǅ*ɓ*Ŝ;}bool Ɗ=false;void Ȥ(bool ɥ){if(ŉ==null)return;if(ɥ){if(!Ɗ)return;ŉ.DampenersOverride=true;Ɗ=false;}
else{ŉ.DampenersOverride=false;Ɗ=true;}}void ɂ(){bool ɦ=y.g;ɧ();if(Ø==E.C&&((ï&&!ɦ)||(!ï&&ɦ))){í=false;ƕ(f.S);å=
"Trip complete";return;}if(ɦ){ƕ(f.d);µ=0;}else{if(Ø==E.D){í=false;ƕ(f.S);å="Holding at home";}else{ƕ(f.U);µ=0;}}}bool Ɂ(R p){if(!é||ŗ.
Count==0||ŉ==null)return false;Vector3D ɨ=p.K;IMyCameraBlock ɩ=null;double ɪ=Ÿ,ɫ=0;foreach(var ɢ in ŗ){if(ɢ==null||!ɢ.
IsWorking)continue;Vector3D ɬ=ɨ-ɢ.GetPosition();double ȉ=ɬ.Length();if(ȉ<1e-3)continue;double ɭ=ɢ.WorldMatrix.Forward.Dot(ɬ/ȉ);if
(ɭ>ɪ){ɪ=ɭ;ɩ=ɢ;ɫ=ȉ;}}if(ɩ==null)return false;if(!ɩ.EnableRaycast)ɩ.EnableRaycast=true;if(!ɩ.CanScan(ɫ+ż))return false;
MyDetectedEntityInfo ɮ=ɩ.Raycast(ɨ);if(ɮ.IsEmpty())return false;if(ɮ.EntityId==p.O)return false;if(ɮ.EntityId==Me.CubeGrid.EntityId)return
false;if(p.O==0){double ɯ=Vector3D.Distance(ɩ.GetPosition(),ɮ.HitPosition??ɨ);return ɯ<ɫ-Ž;}return true;}void Ƈ(){Ŋ.Clear();ŋ
.Clear();ő.Clear();var ɰ=Me.CubeGrid;if(!string.IsNullOrEmpty(Ý))ŉ=GridTerminalSystem.GetBlockWithName(Ý)as
IMyRemoteControl;if(ŉ==null){var ɱ=new List<IMyRemoteControl>();GridTerminalSystem.GetBlocksOfType(ɱ,Ȭ=>Ȭ.CubeGrid==ɰ);ŉ=ɱ.Count>0?ɱ[0]:
null;}GridTerminalSystem.GetBlocksOfType(Ŋ,Ȭ=>Ȭ.CubeGrid==ɰ);GridTerminalSystem.GetBlocksOfType(ŋ,Ȭ=>Ȭ.CubeGrid==ɰ);
GridTerminalSystem.GetBlocksOfType(œ,Ȭ=>Ȭ.CubeGrid==ɰ);GridTerminalSystem.GetBlocksOfType(Ŕ,Ȭ=>Ȭ.CubeGrid==ɰ);GridTerminalSystem.
GetBlocksOfType(Ŗ,Ȭ=>Ȭ.CubeGrid==ɰ);var ɲ=new List<IMyCameraBlock>();GridTerminalSystem.GetBlocksOfType(ɲ,Ȭ=>Ȭ.CubeGrid==ɰ);ŗ.Clear();
foreach(var ɢ in ɲ)if(ɳ(ɢ.CustomName,à))ŗ.Add(ɢ);if(ŗ.Count==0)ŗ.AddRange(ɲ);var ɴ=new List<IMyGasTank>();GridTerminalSystem.
GetBlocksOfType(ɴ,Ȭ=>Ȭ.CubeGrid==ɰ);ŕ.Clear();foreach(var ư in ɴ)if(ư.BlockDefinition.SubtypeName.IndexOf("Hydrogen",StringComparison.
OrdinalIgnoreCase)>=0)ŕ.Add(ư);var ɵ=new List<IMyTextPanel>();GridTerminalSystem.GetBlocksOfType(ɵ,Ȭ=>Ȭ.CubeGrid==ɰ&&ɳ(Ȭ.CustomName,ɶ()))
;foreach(var p in ɵ){string ɷ;float ɸ,ɹ;ɺ(p.CustomName,out ɷ,out ɸ,out ɹ);ɻ(p,ɷ,ɸ,ɹ);}var ɼ=new List<IMyTerminalBlock>();
GridTerminalSystem.GetBlocksOfType(ɼ,Ȭ=>Ȭ.CubeGrid==ɰ&&Ȭ is IMyTextSurfaceProvider&&(Ȭ.CustomData.IndexOf("sf-screens",StringComparison.
OrdinalIgnoreCase)>=0||Ȭ.CustomData.IndexOf("shuttle-screens",StringComparison.OrdinalIgnoreCase)>=0));bool ɽ=false;foreach(var Ȭ in ɼ){
var ɾ=Ȭ as IMyTextSurfaceProvider;var ƌ=new MyIni();if(!ƌ.TryParse(Ȭ.CustomData))continue;string ɿ=ƌ.ContainsSection(
"sf-screens")?"sf-screens":ƌ.ContainsSection("shuttle-screens")?"shuttle-screens":null;if(ɿ==null)continue;var ʀ=new List<MyIniKey>(
);ƌ.GetKeys(ɿ,ʀ);foreach(var ɛ in ʀ){int ʁ;if(!int.TryParse(ɛ.Name.Trim(),out ʁ)||ʁ<0||ʁ>=ɾ.SurfaceCount)continue;string
ɷ;float ɸ,ɹ;ʂ(ƌ.Get(ɛ).ToString(""),out ɷ,out ɸ,out ɹ);ɻ(ɾ.GetSurface(ʁ),ɷ,ɸ,ɹ);}if(Ȭ==Me)ɽ=true;}Œ=Me.GetSurface(0);if(!
ɽ){ʃ(Œ);ɻ(Œ,Ŀ,0f,0f);}}string ɶ(){return Þ.EndsWith("]")?Þ.Substring(0,Þ.Length-1):Þ;}void ɻ(IMyTextSurface ʄ,string ɷ,
float ɸ,float ɹ){if(ʄ==null)return;for(int ȍ=0;ȍ<ő.Count;ȍ++)if(ő[ȍ].Ō==ʄ)return;ʃ(ʄ);ő.Add(new Ő{Ō=ʄ,ō=ɷ,Ŏ=ɸ,ŏ=ɹ});}void ɺ(
string Ƙ,out string ɷ,out float ɸ,out float ɹ){ɷ=Ŀ;ɸ=0f;ɹ=0f;string ʅ=ɶ();int ȍ=Ƙ.IndexOf(ʅ,StringComparison.OrdinalIgnoreCase
);if(ȍ<0)return;int ʆ=ȍ+ʅ.Length;int ʇ=Ƙ.IndexOf(']',ʆ);string ʈ=ʇ>ʆ?Ƙ.Substring(ʆ,ʇ-ʆ):Ƙ.Substring(ʆ);var Ɯ=ʈ.Split(':')
;if(Ɯ.Length>=2&&Ɯ[1].Trim().Length>0)ɷ=ʉ(Ɯ[1]);if(Ɯ.Length>=3){float Ȁ;if(float.TryParse(Ɯ[2].Trim(),out Ȁ)&&Ȁ>0)ɸ=Ȁ;}if
(Ɯ.Length>=4){float Ȁ;if(float.TryParse(Ɯ[3].Trim(),out Ȁ)&&Ȁ>=0)ɹ=Ȁ;}}void ʂ(string ʊ,out string ɷ,out float ɸ,out float
ɹ){ɷ=Ŀ;ɸ=0f;ɹ=0f;if(string.IsNullOrEmpty(ʊ))return;var ʋ=ʊ.Split('/');if(ʋ.Length>=2){float Ȁ;if(float.TryParse(ʋ[1].Trim
(),out Ȁ)&&Ȁ>=0)ɹ=Ȁ;}var Ɯ=ʋ[0].Split('@');ɷ=ʉ(Ɯ[0]);if(Ɯ.Length>=2){float Ȁ;if(float.TryParse(Ɯ[1].Trim(),out Ȁ)&&Ȁ>0)ɸ=
Ȁ;}}string ʉ(string ɝ){switch(ɝ.Trim().ToLowerInvariant()){case ŀ:return ŀ;case Ł:return Ł;case ł:return ł;case Ń:return
Ń;default:return Ŀ;}}void ʃ(IMyTextSurface ʄ){ʄ.ContentType=ContentType.TEXT_AND_IMAGE;ʄ.Font="Monospace";ʄ.Alignment=
TextAlignment.LEFT;ʄ.TextPadding=0f;}IMyShipConnector Ʋ(){foreach(var Ƴ in Ŋ)if(Ƴ.Status==MyShipConnectorStatus.Connected)return Ƴ;
return null;}IMyShipConnector ǔ(string Ƙ){foreach(var Ƴ in Ŋ)if(Ƴ.CustomName==Ƙ)return Ƴ;return null;}bool Ơ(){return Ʋ()!=
null;}bool ƣ(){Vector3D p=ŉ.GetPosition();return Vector3D.DistanceSquared(p,ģ.K)<=Vector3D.DistanceSquared(p,Ĥ.K);}bool Ƣ(){
if(ŉ==null||!ê)return false;Vector3D p=ŉ.GetPosition();double ʌ=ŷ*ŷ;return Vector3D.DistanceSquared(p,ģ.K)<=ʌ||Vector3D.
DistanceSquared(p,Ĥ.K)<=ʌ;}bool ɳ(string Ƙ,string ʍ){return!string.IsNullOrEmpty(ʍ)&&Ƙ.IndexOf(ʍ,StringComparison.OrdinalIgnoreCase)>=0
;}double Ǆ(){return ŉ!=null?ŉ.CalculateShipMass().PhysicalMass:0;}double ǆ(){double ȟ=0,ʎ=0;foreach(var Ƴ in ŋ){var ʏ=Ƴ.
GetInventory();ȟ+=(double)ʏ.CurrentVolume;ʎ+=(double)ʏ.MaxVolume;}return ʎ<=0?0:ȟ/ʎ*100.0;}bool ʑ(long Ȧ){return è&&Ļ<ž&&ʐ(ļ,Ȧ);}
bool ʐ(long ƽ,long Ȭ){return ƽ==0||Ȭ==0||ƽ==Ȭ;}long ʔ(bool ʒ){bool ʓ=ʒ?y.g:!y.g;return ʓ?Ĥ.O:ģ.O;}bool Ǎ(string ʕ,string ɨ){
long Ȧ=ʔ(ʕ=="LAND");if(!ʑ(Ȧ))return true;if(ó&&æ==ʕ)return true;if(!ô||Ġ>=ſ){IGC.SendBroadcastMessage(Ü,"CMD|REQ|"+Û+"|"+ʕ+
"|"+ɨ+"|"+Ȧ);ô=true;æ=ʕ;Ġ=0;ó=false;}return false;}string ǎ(string ʕ){return ç.Length>0?"HOLD: "+ç:"Awaiting tower - "+ʕ;}
void Ƒ(){if(Ř==null)return;while(Ř.HasPendingMessage){var Ʈ=Ř.AcceptMessage();var ʄ=Ʈ.Data as string;if(string.IsNullOrEmpty
(ʄ)||!ʄ.StartsWith("CMD|"))continue;var Ȁ=ʄ.Split('|');if(Ȁ.Length<2)continue;if(Ȁ[1]=="DEPART"){string ʖ=Ȁ.Length>=3?Ȁ[2
]:"*";if(ʖ=="*"||ʖ.Equals(Û,StringComparison.OrdinalIgnoreCase))Ƨ();}else if(Ȁ[1]=="TOWER"){long ɓ=Ȁ.Length>=4?ʗ(Ȁ[3]):0;
long ʘ=ģ.O,ʙ=Ĥ.O;if(ɓ==0||ʙ==0||ɓ==ʘ||ɓ==ʙ){Ļ=0;ļ=ɓ;if(Ȁ.Length>=8&&(ʚ(Ȁ[4],out Ĭ)&ʚ(Ȁ[5],out ĭ)&ʚ(Ȁ[6],out Į)&ʚ(Ȁ[7],out į)
))ľ=true;}}else if(Ȁ[1]=="CLEAR"&&Ȁ.Length>=4&&Ȁ[2].Equals(Û,StringComparison.OrdinalIgnoreCase)&&Ȁ[3]==æ&&ʐ(ļ,ʔ(æ==
"LAND"))){ó=true;ç="";if(æ=="LAND"&&Ȁ.Length>=9&&(ʚ(Ȁ[5],out Ľ.K)&ʚ(Ȁ[6],out Ľ.L)&ʚ(Ȁ[7],out Ľ.M)&ʚ(Ȁ[8],out Ľ.N))){Ľ.Q=Ĥ.Q;Ľ.
O=Ĥ.O;Ľ.P=Ĥ.P;õ=true;}}else if(Ȁ[1]=="HOLD"&&Ȁ.Length>=4&&Ȁ[2].Equals(Û,StringComparison.OrdinalIgnoreCase)&&Ȁ[3]==æ&&ʐ(ļ
,ʔ(æ=="LAND"))){ó=false;ç=Ȁ.Length>=5?Ȁ[4]:"hold";}else if(Ȁ[1]=="PATH"&&Ȁ.Length>=6&&Ȁ[2].Equals(Û,StringComparison.
OrdinalIgnoreCase))ʛ(Ȁ[3],Ȁ[4],Ȁ[5]);}}void ʛ(string ʜ,string ʝ,string ʞ){int ʠ=ʟ(ʜ,0),ʡ=ʟ(ʝ,1);if(ʠ==0||ħ.Count==0)ħ.Clear();if(ʞ.Length
>0){var Ɯ=ʞ.Split(';');for(int ȍ=0;ȍ<Ɯ.Length;ȍ++){Vector3D ɝ;if(Ɯ[ȍ].Length>0&&ʚ(Ɯ[ȍ],out ɝ))ħ.Add(ɝ);}}if(ʠ>=ʡ-1){Ħ=new
List<Vector3D>(ħ);ö=Ħ.Count>0;}}bool ǵ(Vector3D p){if(!ľ)return false;Vector3D ȉ=p-Ĭ;Vector3D ʢ=Vector3D.Cross(ĭ,Į);return
Math.Abs(ȉ.Dot(ʢ))<=į.X&&Math.Abs(ȉ.Dot(Į))<=į.Y&&Math.Abs(ȉ.Dot(ĭ))<=į.Z;}void Ƨ(){if(ĩ==f.U||ĩ==f.d){î=true;å=
"Depart requested";return;}if(ĩ==f.S&&ê&&Ơ()){if(!Ƣ()){å="DEPART: not at a route dock - GO HOME/DEST first";return;}í=true;bool Ƥ=ƣ();if(Ø
==E.D){if(Ƥ)ƕ(f.U);else{y.g=false;ƕ(f.V);}}else ƕ(Ƥ?f.U:f.d);µ=0;î=true;å="Departing now";return;}if(í)å=
"DEPART: already under way";else å=ê?"DEPART: dock first":"DEPART: no route";}double ʣ(){double ȟ=0,Ȓ=0;foreach(var ư in ŕ)if(ư!=null&&ư.IsWorking)
{Ȓ+=ư.Capacity;ȟ+=ư.FilledRatio*ư.Capacity;}return Ȓ<=0?-1:ȟ/Ȓ*100.0;}double ʤ(){double ȟ=0,Ȓ=0;foreach(var Ȭ in Ŗ)if(Ȭ!=
null&&Ȭ.IsWorking){Ȓ+=Ȭ.MaxStoredPower;ȟ+=Ȭ.CurrentStoredPower;}return Ȓ<=0?-1:ȟ/Ȓ*100.0;}bool ǌ(bool ʥ,out string ʦ){double
ʧ=ʣ();double ʨ=ʤ();double Ʈ=1.0+ć/100.0;double ʩ=ą;double ʪ=ʥ?ĳ:Ĕ;if(ʪ>0)ʩ=Math.Max(ʩ,ʪ*Ʈ);double ʫ=Ć;double ʬ=ʥ?Ĵ:ĕ;if(ʬ
>0)ʫ=Math.Max(ʫ,ʬ*Ʈ);if(ʧ>=0&&ʧ<ʩ){ʦ="Hold: H2 "+ʧ.ToString("0")+"% < "+ʩ.ToString("0")+"% to depart";return false;}if(ʨ
>=0&&ʨ<ʫ){ʦ="Hold: Batt "+ʨ.ToString("0")+"% < "+ʫ.ToString("0")+"% to depart";return false;}ʦ="";return true;}void Ǐ(bool
ʥ){ð=ʥ;Ė=ʣ();ė=ʤ();}void ɧ(){if(Ė<0&&ė<0)return;double ʧ=ʣ(),ʨ=ʤ();if(ð){if(Ė>=0&&ʧ>=0)ĳ=Math.Max(0,Ė-ʧ);if(ė>=0&&ʨ>=0)Ĵ=
Math.Max(0,ė-ʨ);}else{if(Ė>=0&&ʧ>=0)Ĕ=Math.Max(0,Ė-ʧ);if(ė>=0&&ʨ>=0)ĕ=Math.Max(0,ė-ʨ);}Ė=-1;ė=-1;ʭ();}void Ɩ(){if(ŉ==null)
return;ŉ.SetAutoPilotEnabled(false);ŉ.ClearWaypoints();Ƕ=false;}string ʯ(){int ɿ=ʮ();if(ɿ<0)return"--:--";return(ɿ/60).
ToString("00")+":"+(ɿ%60).ToString("00");}int ʮ(){if(ŉ==null||!Ƕ||ĵ.Count==0)return-1;if(ķ>=ĵ.Count)return-1;double ɝ=Math.Max(ǹ
(),1.0);return(int)(ʰ()/ɝ);}double ʰ(){if(ŉ==null||!Ƕ||ĵ.Count==0)return 0;if(ķ>=ĵ.Count)return 0;double ȉ=Vector3D.
Distance(ŉ.GetPosition(),ĵ[ķ]);for(int ȍ=ķ;ȍ<ĵ.Count-1;ȍ++)ȉ+=Vector3D.Distance(ĵ[ȍ],ĵ[ȍ+1]);return ȉ;}int ʱ(){switch(Ĺ){case ĸ:
return 6;case ń:return 5;case Ņ:return 8;case ņ:return 8;case Ň:return Ĩ.Count+1;default:return 1;}}void ƫ(int ƻ){if(û){ʲ(ƻ);
return;}int Ƶ=ʱ();ĺ=((ĺ+ƻ)%Ƶ+Ƶ)%Ƶ;}void Ƭ(){if(û){ʳ();û=false;return;}if(Ĺ==ĸ){switch(ĺ){case 0:Ə(í?"STOP":"START");break;case
1:ʴ();break;case 2:Ə("DEPART");break;case 3:Ə("HOME");break;case 4:Ĺ=ń;ĺ=0;break;case 5:Ĺ=Ņ;ĺ=0;break;}}else if(Ĺ==ń){
switch(ĺ){case 0:Ɲ();break;case 1:ƞ();break;case 2:ƨ();å="Route cleared";break;case 3:Ĺ=Ň;ĺ=0;break;case 4:Ĺ=ĸ;ĺ=4;break;}}
else if(Ĺ==Ň){if(ĺ<Ĩ.Count){if(í)å="STOP before switching routes";else Ʃ(Ĩ[ĺ]);}else{Ĺ=ń;ĺ=3;}}else if(Ĺ==Ņ){switch(ĺ){case
0:ʵ(ü);break;case 1:ʵ(ý);break;case 2:ʵ(þ);break;case 3:ʵ(ÿ);break;case 4:ʵ(ā/1000.0);break;case 5:ʵ(Ă);break;case 6:Ĺ=ņ;
ĺ=0;break;case 7:Ĺ=ĸ;ĺ=5;break;}}else if(Ĺ==ņ){switch(ĺ){case 0:ʶ(true);break;case 1:ʶ(false);break;case 2:ʵ(Ą);break;
case 3:ʵ(ą);break;case 4:ʵ(Ć);break;case 5:ʵ(ć);break;case 6:è=!è;Ư("useTower",è?"auto":"off");å="Tower = "+(è?"Auto":"Off")
;break;case 7:Ĺ=Ņ;ĺ=6;break;}}}void ƭ(){if(û){û=false;å="Edit cancelled";return;}if(Ĺ==ņ){Ĺ=Ņ;ĺ=6;}else if(Ĺ==Ň){Ĺ=ń;ĺ=3;
}else if(Ĺ!=ĸ){Ĺ=ĸ;ĺ=0;}}void ʴ(){Ø=Ø==E.B?E.C:Ø==E.C?E.D:E.B;string ʄ=Ø==E.C?"ONETRIP":Ø==E.D?"ONEWAY":"CONTINUOUS";Ư(
"runMode",ʄ);å="Mode = "+ƥ(Ø);}void ʶ(bool ʷ){J ư=ʷ?Ù:Ú;ư=ư==J.F?J.G:ư==J.G?J.H:ư==J.H?J.I:J.F;if(ʷ)Ù=ư;else Ú=ư;Ư(ʷ?
"homeTrigger":"destTrigger",Ʊ(ư));å=(ʷ?"Home":"Dest")+" trigger = "+Ʊ(ư);}void ʵ(double ɝ){û=true;Ģ=ɝ;}double ʸ(){if(Ĺ==Ņ)switch(ĺ){
case 0:return 5;case 1:return 5;case 2:return 5;case 3:return 0.5;case 4:return 1;case 5:return 5;}if(Ĺ==ņ)return 5;return 1
;}void ʲ(int ƻ){Ģ=Math.Round(Ģ-ƻ*ʸ(),2);}void ʳ(){if(Ĺ==Ņ)switch(ĺ){case 0:ü=(float)ȵ(Ģ,5,1000);Ư("cruiseSpeed",ü);break;
case 1:ý=(float)ȵ(Ģ,5,ü);Ư("climbSpeed",ý);break;case 2:þ=(float)ȵ(Ģ,5,ü);Ư("descentSpeed",þ);break;case 3:ÿ=(float)ȵ(Ģ,0.5,
20);Ư("dockSpeed",ÿ);break;case 4:ā=ȵ(Ģ,0,100000)*1000.0;Ư("maxMassKg",ā);break;case 5:Ă=ȵ(Ģ,0,100);Ư("departFill",Ă);
break;}else if(Ĺ==ņ)switch(ĺ){case 2:Ą=ȵ(Ģ,0,3600);Ư("dwellSec",Ą);break;case 3:ą=ȵ(Ģ,0,100);Ư("minHydrogenPct",ą);break;case
4:Ć=ȵ(Ģ,0,100);Ư("minBatteryPct",Ć);break;case 5:ć=ȵ(Ģ,0,200);Ư("fuelMarginPct",ć);break;}å="Saved";}double ȵ(double ɝ,
double ʹ,double ʺ){return ɝ<ʹ?ʹ:ɝ>ʺ?ʺ:ɝ;}void Ư(string ʻ,object ʼ){var ƌ=new MyIni();ƌ.TryParse(Me.CustomData);ƌ.Set("sf",ʻ,ʼ.
ToString());Me.CustomData=ƌ.ToString();}List<string>ʾ(){var ɋ=new List<string>();if(Ĺ==ĸ){ɋ.Add(í?"Stop":"Start");ɋ.Add("Mode: "
+ƥ(Ø));ɋ.Add("Depart Now");ɋ.Add("Go Home");ɋ.Add("Record >>");ɋ.Add("Settings >>");}else if(Ĺ==ń){ɋ.Add("Record Home");ɋ
.Add("Record Dest");ɋ.Add("Clear Route");ɋ.Add("Routes >>");ɋ.Add("<< Back");}else if(Ĺ==Ň){for(int ȍ=0;ȍ<Ĩ.Count;ȍ++)ɋ.
Add((Ĩ[ȍ]==ã?"* ":"  ")+Ĩ[ȍ]);ɋ.Add("<< Back");}else if(Ĺ==Ņ){ɋ.Add("Cruise: "+ʽ(0,ü)+" m/s");ɋ.Add("Climb: "+ʽ(1,ý)+" m/s"
);ɋ.Add("Descend: "+ʽ(2,þ)+" m/s");ɋ.Add("Dock: "+ʽ(3,ÿ)+" m/s");ɋ.Add("MaxMass: "+ʽ(4,ā/1000.0)+"t"+(ā<=0?" off":""));ɋ.
Add("Fill: "+ʽ(5,Ă)+" %");ɋ.Add("Depart >>");ɋ.Add("<< Back");}else if(Ĺ==ņ){ɋ.Add("Home trig: "+Ʊ(Ù));ɋ.Add("Dest trig: "+
Ʊ(Ú));ɋ.Add("Dwell: "+ʽ(2,Ą)+" s");ɋ.Add("Min H2: "+ʽ(3,ą)+" %");ɋ.Add("Min Bat: "+ʽ(4,Ć)+" %");ɋ.Add("Margin: "+ʽ(5,ć)+
" %");ɋ.Add("Tower: "+(è?"Auto":"Off"));ɋ.Add("<< Back");}return ɋ;}string ʽ(int ʁ,double ʿ){bool ˀ=û&&ĺ==ʁ;double ɝ=ˀ?Ģ:ʿ;
string ʄ=ɝ.ToString("0.##");return ˀ?"["+ʄ+"]":ʄ;}string ˁ(){return Ĺ==ń?"RECORD":Ĺ==Ņ?"SETTINGS":Ĺ==ņ?"DEPART":Ĺ==Ň?"ROUTES":
"MAIN";}void Ɛ(){var ˆ=new Dictionary<string,string>();foreach(var ư in ő){string ˇ;if(!ˆ.TryGetValue(ư.ō,out ˇ)){ˇ=ˈ(ˉ(ư.ō),ƃ
);ˆ[ư.ō]=ˇ;}ˊ(ư,ˇ);}Echo(ˈ(ˉ(Ŀ),ƃ));}string ˉ(string ɷ){switch(ɷ){case ŀ:return ˋ();case Ł:return ˌ();case ł:return ˍ();
case Ń:return ˎ();default:return ˏ()+ˋ();}}string ˎ(){var ː=new StringBuilder("-- Telem --\n");if(ŉ==null)return ː.Append(
"no rc").ToString();Vector3D ȥ=ŉ.GetShipVelocities().LinearVelocity;Vector3D Ǖ=ŉ.GetNaturalGravity();double Ȅ=Ǖ.Length();ː.
Append(ˑ()+(í?" [RUN]":" [STOP]")+" t"+µ.ToString("0")+"s\n");ː.Append("Spd "+ŉ.GetShipSpeed().ToString("0.0"));if(Ƕ&&ķ<Ķ.
Count)ː.Append("/"+Math.Min(ǹ(),Ķ[ķ]).ToString("0")+"cap");ː.Append("\nDrt a"+ě.ToString("0.00")+" v"+Ĝ.ToString("0.00")+
" br"+ĝ.ToString("0")+" c"+Ğ.ToString("0")+"\n");if(Ȅ>1e-3)ː.Append("VS "+ȥ.Dot(-Ǖ/Ȅ).ToString("+0.0;-0.0")+" Grav "+(Ȅ/9.81)
.ToString("0.00")+"g\n");else ː.Append("VS (space)\n");double ˠ;if(ŉ.TryGetPlanetElevation(MyPlanetElevation.Surface,out
ˠ))ː.Append("Alt "+ˠ.ToString("0")+"m\n");if(Ƕ&&ĵ.Count>0)ː.Append("WP "+(ķ+1)+"/"+ĵ.Count+" "+(ʰ()/1000.0).ToString(
"0.0")+"km\n");ː.Append("Att "+(ğ*57.2958).ToString("0.0")+"deg\n");double ʧ=ʣ(),ʨ=ʤ();ː.Append("H2 "+(ʧ<0?"n/a":ʧ.ToString(
"0")+"%")+" Bat "+(ʨ<0?"n/a":ʨ.ToString("0")+"%"));return ː.ToString();}string ˡ(){return Û+" v"+A+" "+ˑ()+(í?" [RUN]":
" [STOP]");}string ˏ(){var ː=new StringBuilder();ː.Append(ˡ()).Append('\n');ː.Append("Cargo ").Append(ǆ().ToString("0")).Append(
"% ").Append((Ǆ()/1000.0).ToString("0")).Append("t ").Append((ŉ!=null?ŉ.GetShipSpeed():0).ToString("0")).Append("m/s\n");ː.
Append(ê?("Route "+(ã!=""?ã+" ":"")+ĥ.Count+"wp"):"Route: none").Append('\n');if(Ǻ())ː.Append("ETA ").Append(ʯ()).Append(' ').
Append((ʰ()/1000.0).ToString("0.0")).Append("km\n");ː.Append(å).Append('\n');return ː.ToString();}string ˋ(){var ː=new
StringBuilder();ː.Append("-- ").Append(ˁ()).Append(" --\n");var ˢ=ʾ();for(int ȍ=0;ȍ<ˢ.Count;ȍ++)ː.Append(ȍ==ĺ?"> ":"  ").Append(ˢ[ȍ])
.Append('\n');ː.Append(û?"UP/DN +/-  APPLY save":"UP/DN  APPLY  BACK");return ː.ToString();}string ˌ(){var ː=new
StringBuilder();ː.Append("-- Status --\n");ː.Append(ˑ()).Append(í?" [RUN]":" [STOP]").Append('\n');ː.Append('\n');ː.Append(
"-- Cargo --\n");ː.Append(ǆ().ToString("0")).Append("%  ").Append((Ǆ()/1000.0).ToString("0")).Append("t  ").Append((ŉ!=null?ŉ.
GetShipSpeed():0).ToString("0")).Append("m/s");return ː.ToString();}string ˍ(){var ː=new StringBuilder();ː.Append("-- Trip --\n");ː.
Append(ê?("Route "+(ã!=""?ã+" ":"")+ĥ.Count+"wp"):"Route: none").Append('\n');ː.Append("Phase: ").Append(ˑ()).Append('\n');if(
Ǻ())ː.Append("ETA ").Append(ʯ()).Append("  ").Append((ʰ()/1000.0).ToString("0.0")).Append("km\n");ː.Append(å);return ː.
ToString();}string ˑ(){string ˣ=Ĳ[ĩ].o;if(ĩ==f.W||ĩ==f.X||ĩ==f.Y||ĩ==f.Z||ĩ==f.a||ĩ==f.b||ĩ==f.c)return ˣ+(y.g?" >":" <");return
ˣ;}void ˊ(Ő ư,string ˇ){var ʄ=ư.Ō;if(ʄ==null)return;float ɹ=(float)ȵ(ư.ŏ,0,40);ʄ.TextPadding=ɹ;if(ư.Ŏ>0){ʄ.FontSize=ư.Ŏ;}
else{var Ʈ=ʄ.MeasureStringInPixels(new StringBuilder(ˇ),ʄ.Font,1f);if(Ʈ.X>=1&&Ʈ.Y>=1){float ˤ=Math.Max(0.1f,1f-2f*ɹ/100f);
Vector2 ˬ=ʄ.SurfaceSize*ˤ;float ˮ=Math.Min(ˬ.X/Ʈ.X,ˬ.Y/Ʈ.Y)*0.95f;ʄ.FontSize=(float)ȵ(ˮ,0.4,3.0);}}ʄ.WriteText(ˇ);}string ˈ(
string ˇ,int Ͱ){var ͱ=new StringBuilder();foreach(var Ͳ in ˇ.Split('\n')){if(Ͳ.Length<=Ͱ){ͱ.Append(Ͳ).Append('\n');continue;}
int ͳ=0;foreach(var ƛ in Ͳ.Split(' ')){string ʹ=ƛ;while(ʹ.Length>Ͱ){if(ͳ>0){ͱ.Append('\n');ͳ=0;}ͱ.Append(ʹ.Substring(0,Ͱ)).
Append('\n');ʹ=ʹ.Substring(Ͱ);}if(ͳ==0){ͱ.Append(ʹ);ͳ=ʹ.Length;}else if(ͳ+1+ʹ.Length<=Ͱ){ͱ.Append(' ').Append(ʹ);ͳ+=1+ʹ.Length
;}else{ͱ.Append('\n').Append(ʹ);ͳ=ʹ.Length;}}ͱ.Append('\n');}if(ͱ.Length>0&&ͱ[ͱ.Length-1]=='\n')ͱ.Length--;return ͱ.
ToString();}void ƒ(){double Ͷ=0;int ͷ=-1;if(Ǻ()){Ͷ=ʰ();ͷ=ʮ();}string ʦ=string.Join("|",new[]{Û,Ɨ(),ͷ.ToString(),((int)Ͷ).
ToString(),ǆ().ToString("0"),(Ǆ()/1000.0).ToString("0.0"),í?"1":"0"});IGC.SendBroadcastMessage(Ü,ʦ);}void Ƅ(){var ƌ=new MyIni();
ƌ.TryParse(Me.CustomData);ͺ(ƌ);Me.CustomData=ƌ.ToString();}void Ɔ(){var ƌ=new MyIni();ƌ.TryParse(Me.CustomData);ͺ(ƌ);Me.
CustomData=ƌ.ToString();}void ͺ(MyIni ƌ){string ͻ=Ø==E.C?"ONETRIP":Ø==E.D?"ONEWAY":"CONTINUOUS";ƌ.Set("sf","shipName",Û);ƌ.Set(
"sf","channel",Ü);ƌ.Set("sf","useTower",è?"auto":"off");ƌ.Set("sf","runMode",ͻ);ƌ.Set("sf","homeTrigger",Ʊ(Ù));ƌ.Set("sf",
"destTrigger",Ʊ(Ú));ƌ.Set("sf","remoteName",Ý);ƌ.Set("sf","lcdTag",Þ);ƌ.Set("sf","cruiseSpeed",ü);ƌ.Set("sf","climbSpeed",ý);ƌ.Set(
"sf","descentSpeed",þ);ƌ.Set("sf","dockSpeed",ÿ);ƌ.Set("sf","maxMassKg",ā);ƌ.Set("sf","departFill",Ă);ƌ.Set("sf",
"unloadDrainSec",ă);ƌ.Set("sf","dwellSec",Ą);ƌ.Set("sf","minHydrogenPct",ą);ƌ.Set("sf","minBatteryPct",Ć);ƌ.Set("sf","fuelMarginPct",ć);
ƌ.Set("sf","segMeters",Ĉ);ƌ.Set("sf","turnDegrees",ĉ);ƌ.Set("sf","simplifyMeters",Ċ);ƌ.Set("sf","approachDist",ċ);ƌ.Set(
"sf","holdDist",Č);ƌ.Set("sf","gyroRpmCap",Ā);ƌ.Set("sf","brakeFrac",č);ƌ.Set("sf","cornerLen",Ď);ƌ.Set("sf","gyroGain",ď);ƌ
.Set("sf","gyroDamp",Đ);ƌ.Set("sf","cruiseAttitude",ß);ƌ.Set("sf","dockClearCheck",é);ƌ.Set("sf","cameraTag",à);ƌ.Set(
"sf","dockBlockSec",đ);}void ƅ(){var ƌ=new MyIni();if(!ƌ.TryParse(Me.CustomData))return;ͼ(ƌ);Û=ƌ.Get("sf","shipName").
ToString(Û);Ü=ƌ.Get("sf","channel").ToString(Ü);è=ƌ.Get("sf","useTower").ToString(è?"auto":"off").Trim().ToLowerInvariant()==
"auto";string ͻ=ƌ.Get("sf","runMode").ToString("CONTINUOUS").Trim().ToUpperInvariant();string ͽ="Auto";if(ͻ=="WAITFULL"){Ø=E.B
;ͽ="Cargo";}else Ά(ͻ);Ù=Έ(ƌ.Get("sf","homeTrigger").ToString(ͽ));Ú=Έ(ƌ.Get("sf","destTrigger").ToString("Auto"));Ý=ƌ.Get(
"sf","remoteName").ToString("");Þ=ƌ.Get("sf","lcdTag").ToString(Þ);ü=(float)ƌ.Get("sf","cruiseSpeed").ToDouble(ü);ý=(float)ȵ
(ƌ.Get("sf","climbSpeed").ToDouble(ü),5,ü);þ=(float)ȵ(ƌ.Get("sf","descentSpeed").ToDouble(ü),5,ü);ÿ=(float)ƌ.Get("sf",
"dockSpeed").ToDouble(ÿ);ā=ƌ.Get("sf","maxMassKg").ToDouble(ā);Ă=ƌ.Get("sf","departFill").ToDouble(Ă);ă=ƌ.Get("sf","unloadDrainSec"
).ToDouble(ă);Ą=ƌ.Get("sf","dwellSec").ToDouble(Ą);ą=ȵ(ƌ.Get("sf","minHydrogenPct").ToDouble(ą),0,100);Ć=ȵ(ƌ.Get("sf",
"minBatteryPct").ToDouble(Ć),0,100);ć=Math.Max(0,ƌ.Get("sf","fuelMarginPct").ToDouble(ć));Ĉ=ƌ.Get("sf","segMeters").ToDouble(Ĉ);ĉ=ƌ.Get
("sf","turnDegrees").ToDouble(ĉ);Ċ=ƌ.Get("sf","simplifyMeters").ToDouble(Ċ);ċ=ƌ.Get("sf","approachDist").ToDouble(ċ);Č=
Math.Max(ċ+5,ƌ.Get("sf","holdDist").ToDouble(Č));Ā=(float)ƌ.Get("sf","gyroRpmCap").ToDouble(Ā);č=ȵ(ƌ.Get("sf","brakeFrac").
ToDouble(č),0.1,1.0);Ď=Math.Max(1.0,ƌ.Get("sf","cornerLen").ToDouble(Ď));ď=Math.Max(0.1,ƌ.Get("sf","gyroGain").ToDouble(ď));Đ=
Math.Max(0.0,ƌ.Get("sf","gyroDamp").ToDouble(Đ));string Ή=ƌ.Get("sf","cruiseAttitude").ToString(ß).Trim().ToLowerInvariant()
;ß=(Ή=="level"||Ή=="nose")?Ή:"auto";é=ƌ.Get("sf","dockClearCheck").ToBoolean(é);à=ƌ.Get("sf","cameraTag").ToString(à);đ=
Math.Max(0,ƌ.Get("sf","dockBlockSec").ToDouble(đ));}void Ά(string Ʈ){switch(Ʈ.Trim().ToUpperInvariant()){case"ONETRIP":Ø=E.C
;break;case"ONEWAY":Ø=E.D;break;default:Ø=E.B;break;}}J Έ(string ʄ){switch(ʄ.Trim().ToUpperInvariant()){case"CARGO":
return J.G;case"TIMER":return J.H;case"MANUAL":return J.I;default:return J.F;}}string Ί(string Ƙ){return"route."+Ƙ;}void Ƹ(){
if(ã=="")ã="Main";var ƌ=new MyIni();ƌ.TryParse(Me.CustomData);Ό(ƌ,ã);ƌ.Set("routes","active",ã);Me.CustomData=ƌ.ToString()
;Ύ();}void Ό(MyIni ƌ,string Ƙ){string ʄ=Ί(Ƙ);ƌ.Set(ʄ,"homeConn",á);ƌ.Set(ʄ,"destConn",â);ƌ.Set(ʄ,"homePos",Ώ(ģ.K));ƌ.Set(
ʄ,"homeFwd",Ώ(ģ.L));ƌ.Set(ʄ,"homeUp",Ώ(ģ.M));ƌ.Set(ʄ,"homeConnFwd",Ώ(ģ.N));ƌ.Set(ʄ,"destPos",Ώ(Ĥ.K));ƌ.Set(ʄ,"destFwd",Ώ(
Ĥ.L));ƌ.Set(ʄ,"destUp",Ώ(Ĥ.M));ƌ.Set(ʄ,"destConnFwd",Ώ(Ĥ.N));ƌ.Set(ʄ,"homeBaseId",ģ.O);ƌ.Set(ʄ,"destBaseId",Ĥ.O);ƌ.Set(ʄ,
"homeHoldDist",ģ.P);ƌ.Set(ʄ,"destHoldDist",Ĥ.P);ƌ.Set(ʄ,"homeG",ģ.Q);ƌ.Set(ʄ,"destG",Ĥ.Q);ƌ.Set(ʄ,"destZone",ë?"1":"0");var ː=new
StringBuilder();for(int ȍ=0;ȍ<ĥ.Count;ȍ++){if(ȍ>0)ː.Append(';');ː.Append(Ώ(ĥ[ȍ]));}ƌ.Set(ʄ,"path",ː.ToString());}void ƈ(){var ƌ=new
MyIni();if(!ƌ.TryParse(Me.CustomData))return;ΐ(ƌ);Ύ();string ˀ=ƌ.Get("routes","active").ToString("");if(ˀ==""||!Ĩ.Contains(ˀ)
)ˀ=Ĩ.Count>0?Ĩ[0]:"";if(ˀ==""){ê=false;ã="";return;}ã=ˀ;Α(ƌ,ˀ);}void ͼ(MyIni ƌ){if(!ƌ.ContainsSection("shuttle")||ƌ.
ContainsSection("sf"))return;var ʀ=new List<MyIniKey>();ƌ.GetKeys("shuttle",ʀ);foreach(var ɛ in ʀ)ƌ.Set("sf",ɛ.Name,ƌ.Get(ɛ).ToString(
""));ƌ.DeleteSection("shuttle");Me.CustomData=ƌ.ToString();}void ΐ(MyIni ƌ){if(!ƌ.ContainsSection("route"))return;var Β=
new List<string>();ƌ.GetSections(Β);bool Γ=false;foreach(var ɿ in Β)if(ɿ.StartsWith("route.")){Γ=true;break;}if(!Γ){string[
]ʀ={"homeConn","destConn","homePos","homeFwd","homeUp","homeConnFwd","destPos","destFwd","destUp","destConnFwd",
"homeBaseId","destBaseId","homeHoldDist","destHoldDist","homeG","destG","path","homeDock","destDock"};string Δ=Ί("Main");foreach(var
ʻ in ʀ){var ɝ=ƌ.Get("route",ʻ);if(!ɝ.IsEmpty)ƌ.Set(Δ,ʻ,ɝ.ToString(""));}if(!ƌ.ContainsKey("routes","active"))ƌ.Set(
"routes","active","Main");}ƌ.DeleteSection("route");Me.CustomData=ƌ.ToString();}void Α(MyIni ƌ,string Ƙ){string ʄ=Ί(Ƙ);if(!ƌ.
ContainsSection(ʄ)){ê=false;return;}á=ƌ.Get(ʄ,"homeConn").ToString("");â=ƌ.Get(ʄ,"destConn").ToString("");bool Ζ=Ε(ƌ,ʄ,"homePos",
"homeDock",out ģ.K);bool Η=Ε(ƌ,ʄ,"destPos","destDock",out Ĥ.K);bool Θ=ʚ(ƌ.Get(ʄ,"homeFwd").ToString(""),out ģ.L)&ʚ(ƌ.Get(ʄ,
"homeUp").ToString(""),out ģ.M)&ʚ(ƌ.Get(ʄ,"homeConnFwd").ToString(""),out ģ.N)&ʚ(ƌ.Get(ʄ,"destFwd").ToString(""),out Ĥ.L)&ʚ(ƌ.
Get(ʄ,"destUp").ToString(""),out Ĥ.M)&ʚ(ƌ.Get(ʄ,"destConnFwd").ToString(""),out Ĥ.N);ģ.O=ƌ.Get(ʄ,"homeBaseId").ToInt64(0);Ĥ
.O=ƌ.Get(ʄ,"destBaseId").ToInt64(0);ģ.P=ƌ.Get(ʄ,"homeHoldDist").ToDouble(0);Ĥ.P=ƌ.Get(ʄ,"destHoldDist").ToDouble(0);ģ.Q=ƌ
.Get(ʄ,"homeG").ToDouble(0);Ĥ.Q=ƌ.Get(ʄ,"destG").ToDouble(0);ë=ƌ.Get(ʄ,"destZone").ToString("0")=="1";ĥ.Clear();var ƛ=ƌ.
Get(ʄ,"path").ToString("");if(!string.IsNullOrEmpty(ƛ))foreach(var Ι in ƛ.Split(';')){Vector3D ɝ;if(ʚ(Ι,out ɝ))ĥ.Add(ɝ);}if
(!Θ)Κ();ê=Ζ&&Η&&ĥ.Count>0&&á!=""&&â!="";}void Ύ(){Ĩ.Clear();var ƌ=new MyIni();if(!ƌ.TryParse(Me.CustomData))return;var Β=
new List<string>();ƌ.GetSections(Β);foreach(var ɿ in Β)if(ɿ.StartsWith("route."))Ĩ.Add(ɿ.Substring(6));Ĩ.Sort();}void Ʃ(
string Ƙ){Ƙ=ƴ(Ƙ);var ƌ=new MyIni();ƌ.TryParse(Me.CustomData);if(Ƙ==""||!ƌ.ContainsSection(Ί(Ƙ))){å="No route '"+Ƙ+"'";return;}
ã=Ƙ;Α(ƌ,Ƙ);ƌ.Set("routes","active",Ƙ);Me.CustomData=ƌ.ToString();å="Active route: "+Ƙ+" ("+ĥ.Count+"wp)";}void ƪ(string Ƙ
){Ƙ=ƴ(Ƙ);if(Ƙ==""){å="Usage: DELROUTE <name>";return;}var ƌ=new MyIni();ƌ.TryParse(Me.CustomData);if(!ƌ.ContainsSection(Ί
(Ƙ))){å="No route '"+Ƙ+"'";return;}ƌ.DeleteSection(Ί(Ƙ));Me.CustomData=ƌ.ToString();bool Λ=ã==Ƙ;if(Λ)Μ();else Ύ();å=
"Deleted route '"+Ƙ+"'";}void Μ(){Ύ();var ƌ=new MyIni();ƌ.TryParse(Me.CustomData);if(Ĩ.Count>0){ã=Ĩ[0];Α(ƌ,ã);ƌ.Set("routes","active",ã);
}else{ã="";ê=false;ĥ.Clear();á="";â="";ģ=new R();Ĥ=new R();ƌ.Set("routes","active","");}Me.CustomData=ƌ.ToString();}
string ƴ(string ƛ){if(string.IsNullOrEmpty(ƛ))return"";var ː=new StringBuilder();foreach(char Ƴ in ƛ.Trim()){bool Ν=(Ƴ>='0'&&Ƴ
<='9')||(Ƴ>='A'&&Ƴ<='Z')||(Ƴ>='a'&&Ƴ<='z')||Ƴ=='_'||Ƴ=='-';if(Ν)ː.Append(Ƴ);if(ː.Length>=16)break;}return ː.ToString();}
bool Ε(MyIni ƌ,string Ξ,string Ο,string Π,out Vector3D Ȟ){if(ʚ(ƌ.Get(Ξ,Ο).ToString(""),out Ȟ))return true;return ʚ(ƌ.Get(Ξ,Π
).ToString(""),out Ȟ);}void Κ(){if(ĥ.Count>=2){Vector3D ȗ=Vector3D.Normalize(ĥ[1]-ĥ[0]);Vector3D Ȗ=Vector3D.Normalize(ĥ[ĥ
.Count-1]-ĥ[ĥ.Count-2]);ģ.L=ȗ;ģ.N=-ȗ;Ĥ.L=Ȗ;Ĥ.N=Ȗ;}else{ģ.L=ŉ!=null?ŉ.WorldMatrix.Forward:Vector3D.Forward;Ĥ.L=ģ.L;ģ.N=ģ.L
;Ĥ.N=Ĥ.L;}ģ.M=Ρ(ģ.K);Ĥ.M=Ρ(Ĥ.K);}Vector3D Ρ(Vector3D Ȟ){Vector3D ɓ=ŉ!=null?ŉ.GetNaturalGravity():Vector3D.Zero;return ɓ.
LengthSquared()>1e-3?Vector3D.Normalize(-ɓ):ŉ!=null?ŉ.WorldMatrix.Up:Vector3D.Up;}void ƨ(){if(ã!=""){var ƌ=new MyIni();ƌ.TryParse(Me.
CustomData);ƌ.DeleteSection(Ί(ã));Me.CustomData=ƌ.ToString();}Μ();}void Ɖ(){var ƌ=new MyIni();if(!ƌ.TryParse(Me.CustomData)||!ƌ.
ContainsSection("state"))return;if(ƌ.ContainsKey("state","phase")){int Σ=ƌ.Get("state","phase").ToInt32(-1);ĩ=(Σ>=0&&Σ<=(int)f.e)?(f)Σ:
f.S;y.g=ƌ.Get("state","outbound").ToBoolean(true);ï=ƌ.Get("state","tripStartHome").ToBoolean(true);}else{ƙ(ƌ.Get("state",
"state").ToString("Idle"));}í=ƌ.Get("state","operating").ToBoolean(false);µ=ƌ.Get("state","phaseTimer").ToDouble(0);ĳ=ƌ.Get(
"state","estHydroOut").ToDouble(0);Ĵ=ƌ.Get("state","estBattOut").ToDouble(0);Ĕ=ƌ.Get("state","estHydroHome").ToDouble(0);ĕ=ƌ.
Get("state","estBattHome").ToDouble(0);Ƕ=false;}void ʭ(){var ƌ=new MyIni();ƌ.TryParse(Me.CustomData);ƌ.Set("state",
"estHydroOut",ĳ);ƌ.Set("state","estBattOut",Ĵ);ƌ.Set("state","estHydroHome",Ĕ);ƌ.Set("state","estBattHome",ĕ);Me.CustomData=ƌ.
ToString();}string Ώ(Vector3D ɝ){return ɝ.X.ToString("R")+":"+ɝ.Y.ToString("R")+":"+ɝ.Z.ToString("R");}bool ʚ(string ʄ,out
Vector3D ɝ){ɝ=Vector3D.Zero;if(string.IsNullOrEmpty(ʄ))return false;var p=ʄ.Split(':');if(p.Length!=3)return false;double Τ,Υ,Φ;
if(!double.TryParse(p[0],out Τ)||!double.TryParse(p[1],out Υ)||!double.TryParse(p[2],out Φ))return false;ɝ=new Vector3D(Τ,
Υ,Φ);return true;}int ʟ(string ʄ,int Χ){int Ψ;return int.TryParse(ʄ,out Ψ)?Ψ:Χ;}long ʗ(string ʄ){long Ψ;return long.
TryParse(ʄ,out Ψ)?Ψ:0;}
