// SkippyTower - Space Engineers control tower / status board for the Skippy fleet.
// Generated by MDK2 (Mal.Mdk2.PbPackager) from the SkippyTower project - do not edit
// the deployed script by hand. Source of truth: SkippyTower/Program.cs. Full docs in
// README.md / CHANGELOG.md.
// 
const string A="0.13.0";enum E{B,C,D}string F="SkippyShuttleNet";string G="Main",H="[SF]",I="",J="",K="",L=
"Ready. REGZONE / REGPAD / REGPATH to begin.";E M=E.B;bool N=false,O,P;string Q="";double R=2.5,S=12.0,T,U,V;const double W=2.0,X=6.0,Y=180.0,Z=20.0,a=1.0/6.0;const
int b=18,c=400;IMyBroadcastListener d;long e,f;string g="";Dictionary<string,h>i=new Dictionary<string,h>();Dictionary<
string,j>k=new Dictionary<string,j>();Dictionary<string,l>m=new Dictionary<string,l>();bool n;Vector3D o,p,q,r,s,t;Dictionary<
string,List<Vector3D>>u=new Dictionary<string,List<Vector3D>>();IMyRemoteControl v;List<IMyShipConnector>w=new List<
IMyShipConnector>();List<Vector3D>x=new List<Vector3D>();class h{public string y,z;public int ª,µ,º;public double À,Á;public bool Â;}
class j{public string Ã;public double Á;public long Ä;}class l{public string y,Å="";public Vector3D Æ,Ç,È,É;public List<
Vector3D>Ê=new List<Vector3D>();}
Program
(){Runtime.UpdateFrequency=UpdateFrequency.Update10;f=Me.CubeGrid.EntityId;if(string.IsNullOrWhiteSpace(Me.CustomData))Ë(
);Ì();if(M==E.D)Í();else d=IGC.RegisterBroadcastListener(F);}void
 Main
(string Î,UpdateType Ï){T=Runtime.TimeSinceLastRun.TotalSeconds;if(T<=0||T>0.5)T=a;if(M==E.D){Ð(string.IsNullOrEmpty(Î)?
"":Î.Trim());Ñ();return;}if(!string.IsNullOrEmpty(Î))Ò(Î.Trim());Ó();Ô();if(M==E.B){Õ();Ö();if(!N)Ø();Ù();}Ú();}void Ò(
string Û){string Ü=Û.ToUpperInvariant();if(Ü=="MANUAL"){N=true;Ý();}else if(Ü=="AUTO"){N=false;Ý();}else if(Ü=="RELEASE")Þ();
else if(Ü=="CLEAR")ß(null);else if(Ü.StartsWith("CLEAR "))ß(Û.Substring(6).Trim());else if(Ü.StartsWith("PADFREE "))à(Û.
Substring(8).Trim());}void Ó(){while(d.HasPendingMessage){var á=d.AcceptMessage();var â=á.Data as string;if(â==null)continue;var
ã=â.Split('|');if(ã.Length<2)continue;if(ã[0]=="CMD"){if(M==E.B&&ã[1]=="REQ"&&ã.Length>=5)ä(ã[2],ã[3],ã.Length>=6?å(ã[5],
0):0);else if(ã[1]=="PAD"&&ã.Length>=7)æ(ã[2],ã[3],ã[4],ã[5],ã[6]);else if(ã[1]=="ZONE"&&ã.Length>=6)ç(ã[2],ã[3],ã[4],ã[5
]);else if(ã[1]=="PADPATH"&&ã.Length>=6)è(ã[2],ã[3],ã[4],ã[5]);continue;}if(ã.Length<7)continue;i[ã[0]]=new h{y=ã[0],z=ã[
1],ª=é(ã[2],-1),µ=é(ã[3],0),º=é(ã[4],0),À=ê(ã[5],0),Â=ã[6]=="1",Á=0};}}void ä(string ë,string ì,long í){if(í!=0&&f!=0&&í
!=f)return;if(ë==g){î(ï());return;}j ð;if(k.TryGetValue(ë,out ð)){ð.Ã=ì;ð.Á=0;}else{k[ë]=new j{Ã=ì,Á=0,Ä=e++};}if(g.Length
>0)î("CMD|HOLD|"+ë+"|"+ì+"|traffic");else if(ì=="LAND"&&m.Count>0&&ñ()==null)î("CMD|HOLD|"+ë+"|"+ì+"|no pad");}void Ô(){
foreach(var ò in i.Values)ò.Á+=T;if(k.Count>0){var ó=new List<string>();foreach(var ô in k){ô.Value.Á+=T;if(ô.Value.Á>X)ó.Add(ô
.Key);}foreach(var õ in ó)k.Remove(õ);}}void Õ(){if(g.Length==0)return;V+=T;bool ö=false;h ò;if(!i.TryGetValue(g,out ò)||
ò.Á>Z)ö=true;else if(ò.z=="Faulted"||ò.z=="Idle")ö=true;else if(I=="DEPART"&&ø(ò.z))ö=true;else if(I=="LAND"&&ù(ò.z))ö=
true;else if(V>Y)ö=true;if(ö)Þ();}void Ø(){if(g.Length>0||k.Count==0)return;string ú=null;j û=null;foreach(var ô in k){if(!ü
(ô.Value.Ã))continue;if(û==null||ý(ô.Value,û)){û=ô.Value;ú=ô.Key;}}if(ú==null)return;þ(ú,û.Ã);}bool ý(j ÿ,j Ā){bool ā=ÿ.Ã
=="LAND",Ă=Ā.Ã=="LAND";if(ā!=Ă)return ā;return ÿ.Ä<Ā.Ä;}void ß(string ë){if(g.Length>0||k.Count==0)return;if(ë==null){Ø();
return;}j ð;if(!k.TryGetValue(ë,out ð))return;if(!ü(ð.Ã))return;þ(ë,ð.Ã);}void þ(string ë,string ì){g=ë;I=ì;V=0;J="";k.Remove(
ë);if(ì=="LAND"){J=ñ();if(J!=null)m[J].Å=ë;else J="";}î(ï());ă(ë,ì);}void ă(string ë,string ì){l Ą=null;if(ì=="LAND"&&J.
Length>0)m.TryGetValue(J,out Ą);else if(ì=="DEPART"){foreach(var ð in m.Values)if(ð.Å==ë){Ą=ð;break;}}if(Ą==null||Ą.Ê.Count==0
)return;ą(ë,Ą.Ê);}void ą(string ë,List<Vector3D>Ć){int ć=(Ć.Count+b-1)/b;if(ć==0)return;for(int Ĉ=0;Ĉ<ć;Ĉ++)î("CMD|PATH|"
+ë+"|"+Ĉ+"|"+ć+"|"+ĉ(Ć,Ĉ*b,b));}string ĉ(List<Vector3D>Ć,int Ċ,int ċ){var Č=new StringBuilder();int č=Math.Min(Ċ+ċ,Ć.
Count);for(int Ď=Ċ;Ď<č;Ď++){if(Ď>Ċ)Č.Append(';');Č.Append(ď(Ć[Ď]));}return Č.ToString();}void Ė(string Đ,List<Vector3D>đ){if(
string.IsNullOrEmpty(Đ))return;var Ē=Đ.Split(';');Vector3D ē;foreach(var ĕ in Ē)if(Ĕ(ĕ,out ē))đ.Add(ē);}bool ü(string ì){
return ì!="LAND"||m.Count==0||ñ()!=null;}string ï(){string á="CMD|CLEAR|"+g+"|"+I;if(I=="LAND"&&J.Length>0){var Ą=m[J];á+="|"+
J+"|"+ď(Ą.Æ)+"|"+ď(Ą.Ç)+"|"+ď(Ą.È)+"|"+ď(Ą.É);}return á;}string ñ(){foreach(var Ą in m.Values)if(Ą.Å.Length==0)return Ą.y
;return null;}void Ö(){foreach(var Ą in m.Values){if(Ą.Å.Length==0)continue;h ò;if(!i.TryGetValue(Ą.Å,out ò)||ò.Á>Z)Ą.Å=
"";else if(ò.z=="Faulted"||ò.z=="Idle")Ą.Å="";else if(ø(ò.z))Ą.Å="";}}void æ(string ė,string Ę,string ę,string Ě,string ě)
{Vector3D ð,Ĝ,ĝ,Ğ;if(!(Ĕ(Ę,out ð)&Ĕ(ę,out Ĝ)&Ĕ(Ě,out ĝ)&Ĕ(ě,out Ğ)))return;l Ą;if(!m.TryGetValue(ė,out Ą)){Ą=new l{y=ė};m
[ė]=Ą;}Ą.Æ=ð;Ą.Ç=Ĝ;Ą.È=ĝ;Ą.É=Ğ;ğ();}void ç(string Ġ,string ę,string Ě,string ġ){Vector3D Ğ,Ĝ,ĝ,Ģ;if(!(Ĕ(Ġ,out Ğ)&Ĕ(ę,out
Ĝ)&Ĕ(Ě,out ĝ)&Ĕ(ġ,out Ģ)))return;o=Ğ;p=Ĝ;q=ĝ;r=Ģ;n=true;ģ();}void è(string Ĥ,string ĥ,string Ħ,string Đ){int Ĉ=é(ĥ,-1),ć=
é(Ħ,0);if(Ĉ<0||ć<=0)return;List<Vector3D>đ;if(Ĉ==0||!u.TryGetValue(Ĥ,out đ)){đ=new List<Vector3D>();u[Ĥ]=đ;}Ė(Đ,đ);if(Ĉ==
ć-1){l Ą;if(!m.TryGetValue(Ĥ,out Ą)){Ą=new l{y=Ĥ};m[Ĥ]=Ą;}Ą.Ê=đ;u.Remove(Ĥ);ğ();}}void à(string ė){l Ą;if(m.TryGetValue(ė
,out Ą))Ą.Å="";}void Þ(){g="";I="";V=0;J="";}void Ù(){U+=T;if(U<W)return;U=0;string á="CMD|TOWER|"+G+"|"+f;if(n)á+="|"+ď(
o)+"|"+ď(p)+"|"+ď(q)+"|"+ď(r);î(á);}bool ø(string â){return â=="CruiseToDest"||â=="CruiseToHome";}bool ù(string â){return
â=="Loading"||â=="Unloading";}void î(string ħ){IGC.SendBroadcastMessage(F,ħ);}void Ú(){var Č=new StringBuilder();Č.Append
("== Skippy Tower v").Append(A).Append(" ==\n");if(M==E.B)Č.Append("CONTROL/").Append(N?"MANUAL":"AUTO").Append(
" - zone ").Append(G).Append('\n');else Č.Append("BOARD (passive)\n");Č.Append('\n');if(i.Count==0)Č.Append(
"Waiting for shuttle signal...\n");foreach(var ò in i.Values){if(ò.Á>Z){Č.Append(ò.y).Append(": NO SIGNAL (").Append((int)ò.Á).Append("s)\n\n");continue;
}Č.Append(ò.y).Append(": ").Append(Ĩ(ò.z)).Append('\n');if(ò.ª>=0)Č.Append("   ETA ").Append((ò.ª/60).ToString("00")).
Append(':').Append((ò.ª%60).ToString("00")).Append("   ").Append((ò.µ/1000.0).ToString("0.0")).Append(" km\n");Č.Append(
"   Cargo ").Append(ò.º).Append("%   ").Append(ò.À.ToString("0.0")).Append("t\n");if(M==E.B){if(ò.y==g)Č.Append("   > CLEARED: ").
Append(I).Append('\n');else if(k.ContainsKey(ò.y))Č.Append(N?"   || WAITING (your OK)\n":"   || HOLD (traffic)\n");}Č.Append(
'\n');}if(M==E.B){if(g.Length>0)Č.Append("Slot: ").Append(g).Append(" (").Append(I).Append(")\n");else if(N&&k.Count>0){
string ĩ=null;j Ī=null;foreach(var ô in k)if(Ī==null||ý(ô.Value,Ī)){Ī=ô.Value;ĩ=ô.Key;}Č.Append("Next: ").Append(ĩ).Append(
" (").Append(Ī.Ã).Append(") - run CLEAR\n");}else Č.Append("Slot: free\n");if(n)Č.Append("Zone: ").Append((r.X*2).ToString(
"0")).Append('x').Append((r.Y*2).ToString("0")).Append('x').Append((r.Z*2).ToString("0")).Append("m\n");if(m.Count>0){Č.
Append("-- Pads --\n");foreach(var Ą in m.Values){Č.Append(Ą.y).Append(": ").Append(Ą.Å.Length>0?Ą.Å:"free");if(Ą.Ê.Count>0)Č.
Append(" (").Append(Ą.Ê.Count).Append("wp)");Č.Append('\n');}}}var ī=Č.ToString();Echo(ī);var Ĭ=new List<IMyTextPanel>();
GridTerminalSystem.GetBlocksOfType(Ĭ,Ā=>Ā.CubeGrid.IsSameConstructAs(Me.CubeGrid)&&Ā.CustomName.Contains(H));foreach(var ð in Ĭ){ð.
ContentType=ContentType.TEXT_AND_IMAGE;ð.WriteText(ī);}Me.GetSurface(0).ContentType=ContentType.TEXT_AND_IMAGE;Me.GetSurface(0).
WriteText(ī);}string Ĩ(string â){switch(â){case"Loading":return"Loading at home";case"CruiseToDest":return"En route to station";
case"ApproachDest":return"Docking at station";case"Unloading":return"Unloading at station";case"CruiseToHome":return
"Returning home";case"ApproachHome":return"Docking at home";case"Idle":return"Idle";case"Faulted":return"FAULT - needs attention";
default:return â;}}void Ð(string Û){if(v==null||w.Count==0)Í();if(v==null){L=
"! No Remote Control on this grid - teach needs one.";return;}if(Û.Length>0)ĭ(Û);if(O){if(x.Count<c)Į();bool İ=į()!=null;if(İ&&!P)ı();P=İ;}}void ĭ(string Û){int Ĳ=Û.IndexOf(
' ');string Ü=(Ĳ<0?Û:Û.Substring(0,Ĳ)).ToUpperInvariant();string ĳ=Ĳ<0?"":Û.Substring(Ĳ+1).Trim();if(Ü=="REGZONE")Ĵ(ĳ);else
if(Ü=="REGPAD"){if(ĳ.Length==0){L="REGPAD needs a pad name.";return;}ĵ(ĳ);}else if(Ü=="REGPATH"){string Ě=ĳ.
ToUpperInvariant();if(Ě=="END"){if(O)ı();else L="REGPATH END: nothing recording.";}else if(Ě=="CANCEL"){O=false;K="";x.Clear();L=
"Path recording cancelled.";}else if(ĳ.Length==0)L="REGPATH needs a pad name (or END / CANCEL).";else Ķ(ĳ);}}void Ĵ(string Û){double ķ=20,ĸ=20,Ĺ=20
;var ĺ=Û.Split(new[]{' '},StringSplitOptions.RemoveEmptyEntries);if(ĺ.Length>=1)ķ=ê(ĺ[0],ķ);if(ĺ.Length>=2)ĸ=ê(ĺ[1],ĸ);if
(ĺ.Length>=3)Ĺ=ê(ĺ[2],Ĺ);o=v.GetPosition();p=v.WorldMatrix.Forward;q=v.WorldMatrix.Up;r=new Vector3D(ķ/2,ĸ/2,Ĺ/2);n=true;
î("CMD|ZONE|"+ď(o)+"|"+ď(p)+"|"+ď(q)+"|"+ď(r));L="Zone sent: "+ķ.ToString("0")+"x"+ĸ.ToString("0")+"x"+Ĺ.ToString("0")+
"m.";}void ĵ(string ė){var Ğ=į();if(Ğ==null){L="REGPAD: dock at pad '"+ė+"' first.";return;}Ļ(ė,Ğ);L="Pad '"+ė+
"' pose sent (open-air).";}void Ķ(string ė){O=true;K=ė;x.Clear();s=v.GetPosition();x.Add(s);t=Vector3D.Zero;P=į()!=null;L="Recording path to '"+ė
+"' - fly the corridor in and dock.";}void Į(){Vector3D ð=v.GetPosition();double ļ=Vector3D.Distance(ð,s);if(ļ<0.5)return
;Vector3D Ľ=Vector3D.Normalize(ð-s);double ľ=t==Vector3D.Zero?0:Math.Acos(MathHelper.Clamp(Ľ.Dot(t),-1,1))*180.0/Math.PI;
if(ļ>=R||(ļ>=1.0&&ľ>=S)){x.Add(ð);s=ð;t=Ľ;}}void ı(){var Ğ=į();Ŀ(K,x);if(Ğ!=null){Ļ(K,Ğ);L="Path '"+K+"' sent ("+x.Count+
"wp) + pad pose.";}else{L="Path '"+K+"' sent ("+x.Count+"wp); not docked, no pose.";}O=false;K="";x.Clear();}void Ļ(string ė,
IMyShipConnector Ğ){î("CMD|PAD|"+ė+"|"+ď(v.GetPosition())+"|"+ď(v.WorldMatrix.Forward)+"|"+ď(v.WorldMatrix.Up)+"|"+ď(Ğ.WorldMatrix.
Forward));}void Ŀ(string Ĥ,List<Vector3D>Ć){int ć=(Ć.Count+b-1)/b;if(ć==0)return;for(int Ĉ=0;Ĉ<ć;Ĉ++)î("CMD|PADPATH|"+Ĥ+"|"+Ĉ+
"|"+ć+"|"+ĉ(Ć,Ĉ*b,b));}IMyShipConnector į(){foreach(var Ğ in w)if(Ğ.Status==MyShipConnectorStatus.Connected)return Ğ;return
null;}void Í(){var í=Me.CubeGrid;if(!string.IsNullOrEmpty(Q))v=GridTerminalSystem.GetBlockWithName(Q)as IMyRemoteControl;if(
v==null){var ŀ=new List<IMyRemoteControl>();GridTerminalSystem.GetBlocksOfType(ŀ,Ā=>Ā.CubeGrid==í);v=ŀ.Count>0?ŀ[0]:null;
}w.Clear();GridTerminalSystem.GetBlocksOfType(w,Ā=>Ā.CubeGrid==í);}void Ñ(){var Č=new StringBuilder();Č.Append(
"== Skippy Teach v").Append(A).Append(" ==\n");Č.Append("Ship setup helper (channel ").Append(F).Append(")\n\n");if(v==null)Č.Append(
"! No Remote Control found on this grid.\n");else{bool İ=į()!=null;Č.Append("Zone: ").Append(n?(r.X*2).ToString("0")+"x"+(r.Y*2).ToString("0")+"x"+(r.Z*2).ToString
("0")+"m defined":"not set - run REGZONE").Append('\n');Č.Append("Dock: ").Append(İ?"CONNECTED":"free").Append('\n');if(O
)Č.Append("REC '").Append(K).Append("': ").Append(x.Count).Append(" wp (fly in + dock)\n");Č.Append('\n');}Č.Append(L).
Append('\n');Č.Append("\nCommands: REGZONE [w h d] | REGPATH <pad> | REGPATH END/CANCEL | REGPAD <pad>\n");var ī=Č.ToString();
Echo(ī);var Ĭ=new List<IMyTextPanel>();GridTerminalSystem.GetBlocksOfType(Ĭ,Ā=>Ā.CubeGrid.IsSameConstructAs(Me.CubeGrid)&&Ā.
CustomName.Contains(H));foreach(var ð in Ĭ){ð.ContentType=ContentType.TEXT_AND_IMAGE;ð.WriteText(ī);}Me.GetSurface(0).ContentType=
ContentType.TEXT_AND_IMAGE;Me.GetSurface(0).WriteText(ī);}void Ë(){var Ł=new MyIni();Ł.TryParse(Me.CustomData);ł(Ł);Me.CustomData=Ł
.ToString();}void ł(MyIni Ł){Ł.Set("sf","channel",F);Ł.Set("sf","zone",G);Ł.Set("sf","lcdTag",H);Ł.Set("sf","towerMode",M
==E.C?"board":M==E.D?"teach":"control");Ł.Set("sf","grant",N?"manual":"auto");Ł.Set("sf","remoteName",Q);Ł.Set("sf",
"teachSeg",R);Ł.Set("sf","teachTurn",S);}void Ý(){var Ł=new MyIni();Ł.TryParse(Me.CustomData);Ł.Set("sf","grant",N?"manual":"auto"
);Me.CustomData=Ł.ToString();}void ğ(){var Ł=new MyIni();Ł.TryParse(Me.CustomData);foreach(var Ą in m.Values){string â=
"pad."+Ą.y;Ł.Set(â,"pos",ď(Ą.Æ));Ł.Set(â,"fwd",ď(Ą.Ç));Ł.Set(â,"up",ď(Ą.È));Ł.Set(â,"connFwd",ď(Ą.É));Ł.Set(â,"path",Ń(Ą.Ê));}
Me.CustomData=Ł.ToString();}void ģ(){var Ł=new MyIni();Ł.TryParse(Me.CustomData);Ł.Set("zone","center",ď(o));Ł.Set("zone",
"fwd",ď(p));Ł.Set("zone","up",ď(q));Ł.Set("zone","ext",ď(r));Me.CustomData=Ł.ToString();}string Ń(List<Vector3D>Ć){return Ć.
Count==0?"":ĉ(Ć,0,Ć.Count);}void Ì(){var Ł=new MyIni();if(!Ł.TryParse(Me.CustomData))return;F=Ł.Get("sf","channel").ToString(
F);G=Ł.Get("sf","zone").ToString(G);H=Ł.Get("sf","lcdTag").ToString(H);string ń=Ł.Get("sf","towerMode").ToString(
"control").Trim().ToLowerInvariant();M=ń=="board"?E.C:ń=="teach"?E.D:E.B;N=Ł.Get("sf","grant").ToString("auto").Trim().
ToLowerInvariant()=="manual";Q=Ł.Get("sf","remoteName").ToString(Q);R=Ł.Get("sf","teachSeg").ToDouble(R);S=Ł.Get("sf","teachTurn").
ToDouble(S);n=false;Vector3D Ņ,ņ,Ň,ň;if(Ĕ(Ł.Get("zone","center").ToString(),out Ņ)&Ĕ(Ł.Get("zone","fwd").ToString(),out ņ)&Ĕ(Ł.
Get("zone","up").ToString(),out Ň)&Ĕ(Ł.Get("zone","ext").ToString(),out ň)){o=Ņ;p=ņ;q=Ň;r=ň;n=true;}m.Clear();var ŉ=new
List<string>();Ł.GetSections(ŉ);foreach(var â in ŉ){if(!â.StartsWith("pad."))continue;string ė=â.Substring(4);Vector3D ð,Ĝ,ĝ
,Ğ;if(Ĕ(Ł.Get(â,"pos").ToString(),out ð)&Ĕ(Ł.Get(â,"fwd").ToString(),out Ĝ)&Ĕ(Ł.Get(â,"up").ToString(),out ĝ)&Ĕ(Ł.Get(â,
"connFwd").ToString(),out Ğ)){var Ą=new l{y=ė,Æ=ð,Ç=Ĝ,È=ĝ,É=Ğ};Ė(Ł.Get(â,"path").ToString(),Ą.Ê);m[ė]=Ą;}}}int é(string â,int Ŋ){
int ò;return int.TryParse(â,out ò)?ò:Ŋ;}long å(string â,long Ŋ){long ò;return long.TryParse(â,out ò)?ò:Ŋ;}double ê(string â
,double Ŋ){double ò;return double.TryParse(â,out ò)?ò:Ŋ;}string ď(Vector3D ē){return ē.X.ToString("R")+":"+ē.Y.ToString(
"R")+":"+ē.Z.ToString("R");}bool Ĕ(string â,out Vector3D ē){ē=Vector3D.Zero;if(string.IsNullOrEmpty(â))return false;var ð=â
.Split(':');if(ð.Length!=3)return false;double ŋ,Ō,ō;if(!double.TryParse(ð[0],out ŋ)||!double.TryParse(ð[1],out Ō)||!
double.TryParse(ð[2],out ō))return false;ē=new Vector3D(ŋ,Ō,ō);return true;}
